In [1]:
#Importing the files
import pandas as pd
pathy = "/Users/adi/Desktop/allYearCrime/"
path = "/Users/adi/Desktop/OPE CSS Custom Data 2022-01-06 153842/"
Arrests_Local_State_Police = pd.read_csv(path + "Arrests_Local_State_Police.csv")
Arrests_On_campus_Student_Housing_Facilities = pd.read_csv(path + "Arrests_On_campus_Student_Housing_Facilities.csv")
Arrests_Noncampus = pd.read_csv(path + "Arrests_Noncampus.csv")
Arrests_On_campus =pd.read_csv(path + "Arrests_On_campus.csv")
Arrests_Public_Property =pd.read_csv(path + "Arrests_Public_Property.csv")
Criminal_Offenses_Noncampus =pd.read_csv(path + "Criminal_Offenses_Noncampus.csv")
Criminal_Offenses_On_campus_Student_Housing_Facilities = pd.read_csv(path + "Criminal_Offenses_On_campus_Student_Housing_Facilities.csv")
Criminal_Offenses_On_campus =pd.read_csv(path + "Criminal_Offenses_On_campus.csv")
Criminal_Offenses_Public_Property = pd.read_csv(path + "Criminal_Offenses_Public_Property.csv")
Criminal_Offenses_Reported_by_Local_State_Police =pd.read_csv(path + "Criminal_Offenses_Reported_by_Local_State_Police.csv")
VAWA_Offenses_Reported_by_Local_State_Police = pd.read_csv(path + "VAWA_Offenses_Reported_by_Local_State_Police.csv")
VAWA_Offenses_Public_Property = pd.read_csv(path + "VAWA_Offenses_Public_Property.csv")
VAWA_Offenses_On_campus = pd.read_csv(path + "VAWA_Offenses_On_campus.csv")
VAWA_Offenses_On_campus_Student_Housing_Facilities = pd.read_csv(path + "VAWA_Offenses_On_campus_Student_Housing_Facilities.csv")
VAWA_Offenses_Noncampus = pd.read_csv(path + "VAWA_Offenses_Noncampus.csv")
Disciplinary_Actions_Noncampus = pd.read_csv(path + "Disciplinary_Actions_Noncampus.csv")
Disciplinary_Actions_On_campus = pd.read_csv(path + "Disciplinary_Actions_On_campus.csv")
Disciplinary_Actions_Public_Property = pd.read_csv(path + "Disciplinary_Actions_Public_Property.csv")
Disciplinary_Actions_Reported_by_Local_State_Police = pd.read_csv(path + "Disciplinary_Actions_Reported_by_Local_State_Police.csv")
Disciplinary_Actions_On_campus_Student_Housing_Facilities = pd.read_csv(path + "Disciplinary_Actions_Student_Housing_Facilities.csv")
Hate_Crimes_Noncampus = pd.read_csv(path + "Hate_Crimes_Noncampus.csv")
Hate_Crimes_On_campus_Student_Housing_Facilities = pd.read_csv(path + "Hate_Crimes_On_campus_Student_Housing_Facilities.csv")
Hate_Crimes_On_campus = pd.read_csv(path + "Hate_Crimes_On_campus.csv")
Hate_Crimes_Public_Property = pd.read_csv(path + "Hate_Crimes_Public_Property.csv")
Hate_Crimes_Reported_by_Local_State_Police = pd.read_csv(path + "Hate_Crimes_Reported_by_Local_State_Police.csv")
Unfounded_Crimes = pd.read_csv(path + "Unfounded_Crimes.csv")
#Total_Fires_On_campus_Student_Housing_Facilities = pd.read_csv("/Users/adi/Downloads/OPE CSS Custom Data 2021-12-27 103347/Detailed_Fire_Data.csv")
#Detailed_Fire_Data = pd.read_csv("/Users/adi/Downloads/OPE CSS Custom Data 2021-12-27 103347/Detailed_Fire_Data.csv")
                               

#first_column = df.pop('Name')
  
# insert column using insert(position,column_name,
# first_column) function
#df.insert(0, 'Name', first_column)
#Indexing + Dropping

In [2]:

#Creating a common index
Arrests_Local_State_Police['index'] = Arrests_Local_State_Police['Institution name'].astype(str) + "," +Arrests_Local_State_Police[' Campus Name'].astype(str) + "," + Arrests_Local_State_Police['Institution Size'].astype(str)+ "," + Arrests_Local_State_Police['Survey year'].astype(str) + "," + Arrests_Local_State_Police['Unitid'].astype(str) + "," + Arrests_Local_State_Police['Campus ID'].astype(str) 
Arrests_Local_State_Police = Arrests_Local_State_Police.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)

#FIX THIS
Arrests_On_campus_Student_Housing_Facilities['index'] = Arrests_On_campus_Student_Housing_Facilities['Institution name'].astype(str) + "," +Arrests_On_campus_Student_Housing_Facilities[' Campus Name'].astype(str) + "," + Arrests_On_campus_Student_Housing_Facilities['Institution Size'].astype(str)+ "," + Arrests_On_campus_Student_Housing_Facilities['Survey year'].astype(str) + "," + Arrests_On_campus_Student_Housing_Facilities['Unitid'].astype(str) + "," + Arrests_On_campus_Student_Housing_Facilities['Campus ID'].astype(str) 
Arrests_On_campus_Student_Housing_Facilities = Arrests_On_campus_Student_Housing_Facilities.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Arrests_Noncampus['index'] = Arrests_Noncampus['Institution name'].astype(str) + "," +Arrests_Noncampus[' Campus Name'].astype(str) + "," + Arrests_Noncampus['Institution Size'].astype(str)+ "," + Arrests_Noncampus['Survey year'].astype(str) + "," + Arrests_Noncampus['Unitid'].astype(str) + "," + Arrests_Noncampus['Campus ID'].astype(str) 
Arrests_Noncampus = Arrests_Noncampus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Arrests_On_campus['index'] = Arrests_On_campus['Institution name'].astype(str) + "," +Arrests_On_campus[' Campus Name'].astype(str) + "," + Arrests_On_campus['Institution Size'].astype(str)+ "," + Arrests_On_campus['Survey year'].astype(str) + "," + Arrests_On_campus['Unitid'].astype(str) + "," + Arrests_On_campus['Campus ID'].astype(str) 
Arrests_On_campus = Arrests_On_campus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)

Arrests_Public_Property['index'] =Arrests_Public_Property['Institution name'].astype(str) + "," +Arrests_Public_Property[' Campus Name'].astype(str) + "," + Arrests_Public_Property['Institution Size'].astype(str)+ "," + Arrests_Public_Property['Survey year'].astype(str) + "," + Arrests_Public_Property['Unitid'].astype(str) + "," + Arrests_Public_Property['Campus ID'].astype(str) 
Arrests_Public_Property = Arrests_Public_Property.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)

Criminal_Offenses_Noncampus['index'] =   Criminal_Offenses_Noncampus['Institution name'].astype(str) + "," +Criminal_Offenses_Noncampus[' Campus Name'].astype(str) + "," + Criminal_Offenses_Noncampus['Institution Size'].astype(str)+ "," + Criminal_Offenses_Noncampus['Survey year'].astype(str) + "," + Criminal_Offenses_Noncampus['Unitid'].astype(str) + "," + Criminal_Offenses_Noncampus['Campus ID'].astype(str) 
Criminal_Offenses_Noncampus = Criminal_Offenses_Noncampus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Criminal_Offenses_On_campus_Student_Housing_Facilities['index'] =    Criminal_Offenses_On_campus_Student_Housing_Facilities['Institution name'].astype(str) + "," +Criminal_Offenses_On_campus_Student_Housing_Facilities[' Campus Name'].astype(str) + "," + Criminal_Offenses_On_campus_Student_Housing_Facilities['Institution Size'].astype(str)+ "," + Criminal_Offenses_On_campus_Student_Housing_Facilities['Survey year'].astype(str) + "," + Criminal_Offenses_On_campus_Student_Housing_Facilities['Unitid'].astype(str) + "," + Criminal_Offenses_On_campus_Student_Housing_Facilities['Campus ID'].astype(str) 
Criminal_Offenses_On_campus_Student_Housing_Facilities= Criminal_Offenses_On_campus_Student_Housing_Facilities.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)





Criminal_Offenses_Public_Property['index'] =    Criminal_Offenses_Public_Property['Institution name'].astype(str) + "," +Criminal_Offenses_Public_Property[' Campus Name'].astype(str) + "," + Criminal_Offenses_Public_Property['Institution Size'].astype(str)+ "," + Criminal_Offenses_Public_Property['Survey year'].astype(str) + "," + Criminal_Offenses_Public_Property['Unitid'].astype(str) + "," + Criminal_Offenses_Public_Property['Campus ID'].astype(str) 
Criminal_Offenses_Public_Property= Criminal_Offenses_Public_Property.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Criminal_Offenses_On_campus['index'] =    Criminal_Offenses_On_campus['Institution name'].astype(str) + "," +Criminal_Offenses_On_campus[' Campus Name'].astype(str) + "," + Criminal_Offenses_On_campus['Institution Size'].astype(str)+ "," + Criminal_Offenses_On_campus['Survey year'].astype(str) + "," + Criminal_Offenses_On_campus['Unitid'].astype(str) + "," + Criminal_Offenses_On_campus['Campus ID'].astype(str) 
Criminal_Offenses_On_campus= Criminal_Offenses_On_campus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)




Criminal_Offenses_Reported_by_Local_State_Police['index'] =    Criminal_Offenses_Reported_by_Local_State_Police['Institution name'].astype(str) + "," +Criminal_Offenses_Reported_by_Local_State_Police[' Campus Name'].astype(str) + "," + Criminal_Offenses_Reported_by_Local_State_Police['Institution Size'].astype(str)+ "," + Criminal_Offenses_Reported_by_Local_State_Police['Survey year'].astype(str) + "," + Criminal_Offenses_Reported_by_Local_State_Police['Unitid'].astype(str) + "," + Criminal_Offenses_Reported_by_Local_State_Police['Campus ID'].astype(str) 
Criminal_Offenses_Reported_by_Local_State_Police= Criminal_Offenses_Reported_by_Local_State_Police.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)

VAWA_Offenses_Reported_by_Local_State_Police['index'] =   VAWA_Offenses_Reported_by_Local_State_Police['Institution name'].astype(str) + "," +VAWA_Offenses_Reported_by_Local_State_Police[' Campus Name'].astype(str) + "," + VAWA_Offenses_Reported_by_Local_State_Police['Institution Size'].astype(str)+ "," + VAWA_Offenses_Reported_by_Local_State_Police['Survey year'].astype(str) + "," + VAWA_Offenses_Reported_by_Local_State_Police['Unitid'].astype(str) + "," + VAWA_Offenses_Reported_by_Local_State_Police['Campus ID'].astype(str) 
VAWA_Offenses_Reported_by_Local_State_Police = VAWA_Offenses_Reported_by_Local_State_Police.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


VAWA_Offenses_Public_Property['index'] =    VAWA_Offenses_Public_Property['Institution name'].astype(str) + "," +VAWA_Offenses_Public_Property[' Campus Name'].astype(str) + "," + VAWA_Offenses_Public_Property['Institution Size'].astype(str)+ "," + VAWA_Offenses_Public_Property['Survey year'].astype(str) + "," + VAWA_Offenses_Public_Property['Unitid'].astype(str) + "," + VAWA_Offenses_Public_Property['Campus ID'].astype(str) 
VAWA_Offenses_Public_Property= VAWA_Offenses_Public_Property.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)





VAWA_Offenses_On_campus['index'] =    VAWA_Offenses_On_campus['Institution name'].astype(str) + "," +VAWA_Offenses_On_campus[' Campus Name'].astype(str) + "," + VAWA_Offenses_On_campus['Institution Size'].astype(str)+ "," + VAWA_Offenses_On_campus['Survey year'].astype(str) + "," + VAWA_Offenses_On_campus['Unitid'].astype(str) + "," + VAWA_Offenses_On_campus['Campus ID'].astype(str) 
VAWA_Offenses_On_campus= VAWA_Offenses_On_campus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



VAWA_Offenses_On_campus_Student_Housing_Facilities['index'] =    VAWA_Offenses_On_campus_Student_Housing_Facilities['Institution name'].astype(str) + "," +VAWA_Offenses_On_campus_Student_Housing_Facilities[' Campus Name'].astype(str) + "," + VAWA_Offenses_On_campus_Student_Housing_Facilities['Institution Size'].astype(str)+ "," + VAWA_Offenses_On_campus_Student_Housing_Facilities['Survey year'].astype(str) + "," + VAWA_Offenses_On_campus_Student_Housing_Facilities['Unitid'].astype(str) + "," + VAWA_Offenses_On_campus_Student_Housing_Facilities['Campus ID'].astype(str) 
VAWA_Offenses_On_campus_Student_Housing_Facilities= VAWA_Offenses_On_campus_Student_Housing_Facilities.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


VAWA_Offenses_Noncampus['index'] = VAWA_Offenses_Noncampus['Institution name'].astype(str) + "," +VAWA_Offenses_Noncampus[' Campus Name'].astype(str) + "," + VAWA_Offenses_Noncampus['Institution Size'].astype(str)+ "," + VAWA_Offenses_Noncampus['Survey year'].astype(str) + "," + VAWA_Offenses_Noncampus['Unitid'].astype(str) + "," + VAWA_Offenses_Noncampus['Campus ID'].astype(str) 
VAWA_Offenses_Noncampus = VAWA_Offenses_Noncampus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Disciplinary_Actions_Reported_by_Local_State_Police['index'] =   Disciplinary_Actions_Reported_by_Local_State_Police['Institution name'].astype(str) + "," +Disciplinary_Actions_Reported_by_Local_State_Police[' Campus Name'].astype(str) + "," + Disciplinary_Actions_Reported_by_Local_State_Police['Institution Size'].astype(str)+ "," + Disciplinary_Actions_Reported_by_Local_State_Police['Survey year'].astype(str) + "," + Disciplinary_Actions_Reported_by_Local_State_Police['Unitid'].astype(str) + "," + Disciplinary_Actions_Reported_by_Local_State_Police['Campus ID'].astype(str) 
Disciplinary_Actions_Reported_by_Local_State_Police = Disciplinary_Actions_Reported_by_Local_State_Police.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Disciplinary_Actions_Public_Property['index'] =    Disciplinary_Actions_Public_Property['Institution name'].astype(str) + "," +Disciplinary_Actions_Public_Property[' Campus Name'].astype(str) + "," + Disciplinary_Actions_Public_Property['Institution Size'].astype(str)+ "," + Disciplinary_Actions_Public_Property['Survey year'].astype(str) + "," + Disciplinary_Actions_Public_Property['Unitid'].astype(str) + "," + Disciplinary_Actions_Public_Property['Campus ID'].astype(str) 
Disciplinary_Actions_Public_Property= Disciplinary_Actions_Public_Property.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Disciplinary_Actions_On_campus['index'] =    Disciplinary_Actions_On_campus['Institution name'].astype(str) + "," +Disciplinary_Actions_On_campus[' Campus Name'].astype(str) + "," + Disciplinary_Actions_On_campus['Institution Size'].astype(str)+ "," + Disciplinary_Actions_On_campus['Survey year'].astype(str) + "," + Disciplinary_Actions_On_campus['Unitid'].astype(str) + "," + Disciplinary_Actions_On_campus['Campus ID'].astype(str) 
Disciplinary_Actions_On_campus= Disciplinary_Actions_On_campus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Disciplinary_Actions_On_campus_Student_Housing_Facilities['index'] =    Disciplinary_Actions_On_campus_Student_Housing_Facilities['Institution name'].astype(str) + "," +Disciplinary_Actions_On_campus_Student_Housing_Facilities[' Campus Name'].astype(str) + "," + Disciplinary_Actions_On_campus_Student_Housing_Facilities['Institution Size'].astype(str)+ "," + Disciplinary_Actions_On_campus_Student_Housing_Facilities['Survey year'].astype(str) + "," + Disciplinary_Actions_On_campus_Student_Housing_Facilities['Unitid'].astype(str) + "," + Disciplinary_Actions_On_campus_Student_Housing_Facilities['Campus ID'].astype(str) 
Disciplinary_Actions_On_campus_Student_Housing_Facilities= Disciplinary_Actions_On_campus_Student_Housing_Facilities.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Disciplinary_Actions_Noncampus ['index'] = Disciplinary_Actions_Noncampus ['Institution name'].astype(str) + "," +Disciplinary_Actions_Noncampus [' Campus Name'].astype(str) + "," + Disciplinary_Actions_Noncampus ['Institution Size'].astype(str)+ "," + Disciplinary_Actions_Noncampus ['Survey year'].astype(str) + "," + Disciplinary_Actions_Noncampus ['Unitid'].astype(str) + "," + Disciplinary_Actions_Noncampus ['Campus ID'].astype(str) 
Disciplinary_Actions_Noncampus  = Disciplinary_Actions_Noncampus .drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)

Hate_Crimes_Reported_by_Local_State_Police['index'] =   Hate_Crimes_Reported_by_Local_State_Police['Institution name'].astype(str) + "," +Hate_Crimes_Reported_by_Local_State_Police[' Campus Name'].astype(str) + "," + Hate_Crimes_Reported_by_Local_State_Police['Institution Size'].astype(str)+ "," + Hate_Crimes_Reported_by_Local_State_Police['Survey year'].astype(str) + "," + Hate_Crimes_Reported_by_Local_State_Police['Unitid'].astype(str) + "," + Hate_Crimes_Reported_by_Local_State_Police['Campus ID'].astype(str) 
Hate_Crimes_Reported_by_Local_State_Police = Hate_Crimes_Reported_by_Local_State_Police.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Hate_Crimes_Public_Property['index'] =    Hate_Crimes_Public_Property['Institution name'].astype(str) + "," +Hate_Crimes_Public_Property[' Campus Name'].astype(str) + "," + Hate_Crimes_Public_Property['Institution Size'].astype(str)+ "," + Hate_Crimes_Public_Property['Survey year'].astype(str) + "," + Hate_Crimes_Public_Property['Unitid'].astype(str) + "," + Hate_Crimes_Public_Property['Campus ID'].astype(str) 
Hate_Crimes_Public_Property= Hate_Crimes_Public_Property.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)




Hate_Crimes_On_campus['index'] =    Hate_Crimes_On_campus['Institution name'].astype(str) + "," +Hate_Crimes_On_campus[' Campus Name'].astype(str) + "," + Hate_Crimes_On_campus['Institution Size'].astype(str)+ "," + Hate_Crimes_On_campus['Survey year'].astype(str) + "," + Hate_Crimes_On_campus['Unitid'].astype(str) + "," + Hate_Crimes_On_campus['Campus ID'].astype(str) 
Hate_Crimes_On_campus= Hate_Crimes_On_campus.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Hate_Crimes_On_campus_Student_Housing_Facilities['index'] =    Hate_Crimes_On_campus_Student_Housing_Facilities['Institution name'].astype(str) + "," +Hate_Crimes_On_campus_Student_Housing_Facilities[' Campus Name'].astype(str) + "," + Hate_Crimes_On_campus_Student_Housing_Facilities['Institution Size'].astype(str)+ "," + Hate_Crimes_On_campus_Student_Housing_Facilities['Survey year'].astype(str) + "," + Hate_Crimes_On_campus_Student_Housing_Facilities['Unitid'].astype(str) + "," + Hate_Crimes_On_campus_Student_Housing_Facilities['Campus ID'].astype(str) 
Hate_Crimes_On_campus_Student_Housing_Facilities= Hate_Crimes_On_campus_Student_Housing_Facilities.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)


Hate_Crimes_Noncampus['index'] = Hate_Crimes_Noncampus ['Institution name'].astype(str) + "," +Hate_Crimes_Noncampus [' Campus Name'].astype(str) + "," + Hate_Crimes_Noncampus ['Institution Size'].astype(str)+ "," + Hate_Crimes_Noncampus ['Survey year'].astype(str) + "," + Hate_Crimes_Noncampus ['Unitid'].astype(str) + "," + Hate_Crimes_Noncampus ['Campus ID'].astype(str) 
Hate_Crimes_Noncampus  = Hate_Crimes_Noncampus .drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)



Unfounded_Crimes['index'] =   Unfounded_Crimes['Institution name'].astype(str) + "," +Unfounded_Crimes[' Campus Name'].astype(str) + "," + Unfounded_Crimes['Institution Size'].astype(str)+ "," + Unfounded_Crimes['Survey year'].astype(str) + "," + Unfounded_Crimes['Unitid'].astype(str) + "," + Unfounded_Crimes['Campus ID'].astype(str) 
Unfounded_Crimes = Unfounded_Crimes.drop(['Survey year','Unitid','Campus ID','Institution name'," Campus Name",'Institution Size'],axis = 1)





#my_list = list(Arrests_Public_Property)
#print (my_list)

In [3]:
#custom columns for arrests
Arrests_Local_State_Police['Arrests-Liquor Law/Drug Abuse Violation'] = Arrests_Local_State_Police['Drug law violations'] + Arrests_Local_State_Police['Liquor law violations']
Arrests_Local_State_Police['Arrests-Weapon Possession'] = Arrests_Local_State_Police['Illegal weapons possession']
Arrests_Local_State_Police = Arrests_Local_State_Police[['index','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession']]
Arrests_On_campus_Student_Housing_Facilities['Arrests-Liquor Law/Drug Abuse Violation'] = Arrests_On_campus_Student_Housing_Facilities['Drug law violations'] + Arrests_On_campus_Student_Housing_Facilities['Liquor law violations']
Arrests_On_campus_Student_Housing_Facilities['Arrests-Weapon Possession'] = Arrests_On_campus_Student_Housing_Facilities['Illegal weapons possession']
Arrests_On_campus_Student_Housing_Facilities = Arrests_On_campus_Student_Housing_Facilities[['index','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession']]
Arrests_On_campus['Arrests-Liquor Law/Drug Abuse Violation'] = Arrests_On_campus['Drug law violations'] + Arrests_On_campus['Liquor law violations']
Arrests_On_campus['Arrests-Weapon Possession'] = Arrests_On_campus['Illegal weapons possession']
Arrests_On_campus = Arrests_On_campus[['index','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession']]
Arrests_Public_Property['Arrests-Liquor Law/Drug Abuse Violation'] = Arrests_Public_Property['Drug law violations'] + Arrests_Public_Property['Liquor law violations']
Arrests_Public_Property['Arrests-Weapon Possession'] = Arrests_Public_Property['Illegal weapons possession']
Arrests_Public_Property = Arrests_Public_Property[['index','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession']]
Arrests_Noncampus['Arrests-Liquor Law/Drug Abuse Violation'] = Arrests_Noncampus['Drug law violations'] + Arrests_Noncampus['Liquor law violations']
Arrests_Noncampus['Arrests-Weapon Possession'] = Arrests_Noncampus['Illegal weapons possession']
Arrests_Noncampus = Arrests_Noncampus[['index','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession']]

a1 = Arrests_Public_Property
a12 = pd.merge(a1,Arrests_On_campus, on = "index", how = "outer",suffixes = ("_PP","_OC"))
a123 = pd.merge(a12,Arrests_Noncampus,on = "index", how = "outer",suffixes = ("","_NC"))
a1234 = pd.merge(a123,Arrests_On_campus_Student_Housing_Facilities,on = "index", how = "outer", suffixes = ("","_SHF"))
arrests = pd.merge(a1234,Arrests_Local_State_Police ,on = "index", how = "outer", suffixes = ("","_LSP"))
arrests = arrests.fillna(0)

#arrests['(Arrests)Liquor Law/Drug Abuse Violation'] = arrests['Arrests-Liquor Law/Drug Abuse Violation_PP'] + arrests['Arrests-Liquor Law/Drug Abuse Violation'] + arrests['Arrests-Liquor Law/Drug Abuse Violation_OC'] + arrests['Arrests-Liquor Law/Drug Abuse Violation_SHF'] + arrests['Arrests-Liquor Law/Drug Abuse Violation_LSP']
#arrests['(Arrests)Weapon Possession'] = arrests['Arrests-Weapon Possession_PP'] + arrests['Arrests-Weapon Possession'] + arrests['Arrests-Weapon Possession_OC'] + arrests['Arrests-Weapon Possession_SHF'] + arrests['Arrests-Weapon Possession_LSP']
arrests = arrests.fillna(0)
arrests['Arrests-Liquor Law/Drug Abuse Violation_NC'] = arrests['Arrests-Liquor Law/Drug Abuse Violation']
arrests['Arrests-Weapon Possession_NC'] = arrests['Arrests-Weapon Possession']
arrests = arrests[['index','Arrests-Liquor Law/Drug Abuse Violation_OC','Arrests-Liquor Law/Drug Abuse Violation','Arrests-Weapon Possession_OC','Arrests-Weapon Possession']]
arrests

,index,Arrests-Liquor Law/Drug Abuse Violation_OC,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession_OC,Arrests-Weapon Possession
0,"A T Still University of Health Sciences,Missou...",0.0,0.0,0,0.0
1,"Aaniiih Nakoda College,Aaniiih Nakoda College,...",0.0,0.0,0,0.0
2,"Abilene Christian University,ACU-Abilene,4673....",0.0,0.0,0,0.0
3,"Abraham Baldwin Agricultural College,ABAC main...",18.0,0.0,0,0.0
4,"Abraham Baldwin Agricultural College,ABAC on t...",0.0,0.0,0,0.0
...,...,...,...,...,...
145210,"Zane State College,Main Campus,2262.0,2019,204...",0.0,0.0,0,0.0
145211,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0,0.0
145212,"ZMS The Academy,Main Campus,125.0,2019,486248,1",0.0,0.0,0,0.0
145213,Cortiva Institute-Pennsylvania School of Muscl...,0.0,0.0,0,0.0
145214,"Won Institute of Graduate Studies,Main Campus,...",0.0,0.0,0,0.0

In [4]:
#Custom Columns for DA
Disciplinary_Actions_Reported_by_Local_State_Police['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] = Disciplinary_Actions_Reported_by_Local_State_Police['Drug law violations'] + Disciplinary_Actions_Reported_by_Local_State_Police['Liquor law violations']
Disciplinary_Actions_Reported_by_Local_State_Police['Disciplinary_Actions-Weapon Possession'] = Disciplinary_Actions_Reported_by_Local_State_Police['Illegal weapons possession']
Disciplinary_Actions_Reported_by_Local_State_Police = Disciplinary_Actions_Reported_by_Local_State_Police[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation','Disciplinary_Actions-Weapon Possession']]
Disciplinary_Actions_On_campus_Student_Housing_Facilities['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] = Disciplinary_Actions_On_campus_Student_Housing_Facilities['Drug law violations'] + Disciplinary_Actions_On_campus_Student_Housing_Facilities['Liquor law violations']
Disciplinary_Actions_On_campus_Student_Housing_Facilities['Disciplinary_Actions-Weapon Possession'] = Disciplinary_Actions_On_campus_Student_Housing_Facilities['Illegal weapons possession']
Disciplinary_Actions_On_campus_Student_Housing_Facilities = Disciplinary_Actions_On_campus_Student_Housing_Facilities[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation','Disciplinary_Actions-Weapon Possession']]
Disciplinary_Actions_On_campus['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] = Disciplinary_Actions_On_campus['Drug law violations'] + Disciplinary_Actions_On_campus['Liquor law violations']
Disciplinary_Actions_On_campus['Disciplinary_Actions-Weapon Possession'] = Disciplinary_Actions_On_campus['Illegal weapons possession']
Disciplinary_Actions_On_campus = Disciplinary_Actions_On_campus[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation','Disciplinary_Actions-Weapon Possession']]
Disciplinary_Actions_Public_Property['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] = Disciplinary_Actions_Public_Property['Drug law violations'] + Disciplinary_Actions_Public_Property['Liquor law violations']
Disciplinary_Actions_Public_Property['Disciplinary_Actions-Weapon Possession'] = Disciplinary_Actions_Public_Property['Illegal weapons possession']
Disciplinary_Actions_Public_Property = Disciplinary_Actions_Public_Property[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation','Disciplinary_Actions-Weapon Possession']]
Disciplinary_Actions_Noncampus['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] = Disciplinary_Actions_Noncampus['Drug law violations'] + Disciplinary_Actions_Noncampus['Liquor law violations']
Disciplinary_Actions_Noncampus['Disciplinary_Actions-Weapon Possession'] = Disciplinary_Actions_Noncampus['Illegal weapons possession']
Disciplinary_Actions_Noncampus = Disciplinary_Actions_Noncampus[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation','Disciplinary_Actions-Weapon Possession']]


d2 = pd.merge(Disciplinary_Actions_Reported_by_Local_State_Police,Disciplinary_Actions_Public_Property,on = "index",how = "outer",suffixes = ("_LSP","_PP"))
d3 =  pd.merge(d2,Disciplinary_Actions_On_campus,on = "index",how = "outer",suffixes = ("","_OC"))
d4 = pd.merge(d3,Disciplinary_Actions_On_campus_Student_Housing_Facilities,on = "index",how = "outer",suffixes = ("","_SHF"))
d5 = pd.merge(d4,Disciplinary_Actions_Noncampus,on = "index",how = "outer",suffixes = ("","_NC"))

d5 = d5.fillna(0)
d5['(Disciplinary Action)Liquor Law/Drug Abuse Violation'] = d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation_LSP'] + d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation_PP'] + d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'] + d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation_SHF'] + d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation_NC']  
d5['(Disciplinary Action)Weapon Possession'] = d5['Disciplinary_Actions-Weapon Possession_LSP'] + d5['Disciplinary_Actions-Weapon Possession_PP'] + d5['Disciplinary_Actions-Weapon Possession'] + d5['Disciplinary_Actions-Weapon Possession_SHF'] + d5['Disciplinary_Actions-Weapon Possession_NC']  
d5['Disciplinary_Actions-Weapon Possession_OC'] = d5['Disciplinary_Actions-Weapon Possession']
d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation_OC'] = d5['Disciplinary_Actions-Liquor Law/Drug Abuse Violation']

d5 = d5.fillna(0)
#d5 = d5[['index','(Disciplinary Action)Liquor Law/Drug Abuse Violation','(Disciplinary Action)Weapon Possession']]
d5 = d5[['index','Disciplinary_Actions-Liquor Law/Drug Abuse Violation_NC','Disciplinary_Actions-Liquor Law/Drug Abuse Violation_OC','Disciplinary_Actions-Weapon Possession_NC','Disciplinary_Actions-Weapon Possession_OC']]

In [5]:
#Custom Columns for Criminal Offenses

#Criminal_Offenses_Noncampus['Sex Offences'] = Criminal_Offenses_Noncampus['Rape'] + Criminal_Offenses_Noncampus['Statutory rape'] + Criminal_Offenses_Noncampus['Fondling'] + Criminal_Offenses_Noncampus['Incest']
Criminal_Offenses_Noncampus['Burglary/Break ins'] =  Criminal_Offenses_Noncampus['Burglary'] 
Criminal_Offenses_Noncampus['Motor vehicle theft'] = Criminal_Offenses_Noncampus['Motor vehicle theft']
Criminal_Offenses_Noncampus['Violent Crime'] = Criminal_Offenses_Noncampus['Robbery'] + Criminal_Offenses_Noncampus['Murder/Non-negligent manslaughter'] + Criminal_Offenses_Noncampus['Negligent manslaughter'] + Criminal_Offenses_Noncampus['Aggravated assault']
Criminal_Offenses_Noncampus = Criminal_Offenses_Noncampus[['index','Burglary/Break ins','Motor vehicle theft','Violent Crime','Rape','Statutory rape','Fondling']]
Criminal_Offenses_Noncampus = Criminal_Offenses_Noncampus.fillna(0)

#Criminal_Offenses_On_campus_Student_Housing_Facilities['Sex Offences'] = Criminal_Offenses_On_campus_Student_Housing_Facilities['Rape'] + Criminal_Offenses_On_campus_Student_Housing_Facilities['Statutory rape'] + Criminal_Offenses_On_campus_Student_Housing_Facilities['Fondling'] + Criminal_Offenses_On_campus_Student_Housing_Facilities['Incest']
Criminal_Offenses_On_campus_Student_Housing_Facilities['Burglary/Break ins'] =  Criminal_Offenses_On_campus_Student_Housing_Facilities['Burglary'] 
Criminal_Offenses_On_campus_Student_Housing_Facilities['Motor vehicle theft'] =  Criminal_Offenses_On_campus_Student_Housing_Facilities['Motor vehicle theft']
Criminal_Offenses_On_campus_Student_Housing_Facilities['Violent Crime'] = Criminal_Offenses_On_campus_Student_Housing_Facilities['Robbery'] + Criminal_Offenses_On_campus_Student_Housing_Facilities['Murder/Non-negligent manslaughter'] + Criminal_Offenses_On_campus_Student_Housing_Facilities['Negligent manslaughter']+ Criminal_Offenses_On_campus_Student_Housing_Facilities['Aggravated assault']
Criminal_Offenses_On_campus_Student_Housing_Facilities = Criminal_Offenses_On_campus_Student_Housing_Facilities[['index','Burglary/Break ins','Motor vehicle theft','Violent Crime','Rape','Statutory rape','Fondling']]
Criminal_Offenses_On_campus_Student_Housing_Facilities = Criminal_Offenses_On_campus_Student_Housing_Facilities.fillna(0)

#Criminal_Offenses_Public_Property['Sex Offences'] = Criminal_Offenses_Public_Property['Rape'] + Criminal_Offenses_Public_Property['Statutory rape'] + Criminal_Offenses_Public_Property['Fondling'] + Criminal_Offenses_Public_Property['Incest']
Criminal_Offenses_Public_Property['Burglary/Break ins'] =  Criminal_Offenses_Public_Property['Burglary']  
Criminal_Offenses_Public_Property['Motor vehicle theft'] = Criminal_Offenses_Public_Property['Motor vehicle theft']
Criminal_Offenses_Public_Property['Violent Crime'] = Criminal_Offenses_Public_Property['Robbery'] + Criminal_Offenses_Public_Property['Murder/Non-negligent manslaughter'] + Criminal_Offenses_Public_Property['Negligent manslaughter']+ Criminal_Offenses_Public_Property['Aggravated assault']
Criminal_Offenses_Public_Property = Criminal_Offenses_Public_Property[['index','Burglary/Break ins','Motor vehicle theft','Violent Crime','Rape','Statutory rape','Fondling']]
Criminal_Offenses_Public_Property = Criminal_Offenses_Public_Property.fillna(0)

#Criminal_Offenses_On_campus['Sex Offences'] = Criminal_Offenses_On_campus['Rape'] + Criminal_Offenses_On_campus['Statutory rape'] + Criminal_Offenses_On_campus['Fondling'] + Criminal_Offenses_On_campus['Incest']
Criminal_Offenses_On_campus['Burglary/Break ins'] =  Criminal_Offenses_On_campus['Burglary'] 
Criminal_Offenses_On_campus['Motor vehicle theft']= Criminal_Offenses_On_campus['Motor vehicle theft']
Criminal_Offenses_On_campus['Violent Crime'] = Criminal_Offenses_On_campus['Robbery'] + Criminal_Offenses_On_campus['Murder/Non-negligent manslaughter'] + Criminal_Offenses_On_campus['Negligent manslaughter'] + Criminal_Offenses_On_campus['Aggravated assault']
Criminal_Offenses_On_campus = Criminal_Offenses_On_campus[['index','Burglary/Break ins','Motor vehicle theft','Violent Crime','Rape','Statutory rape','Fondling']]
Criminal_Offenses_On_campus = Criminal_Offenses_On_campus.fillna(0)

#Criminal_Offenses_Reported_by_Local_State_Police['Sex Offences'] = Criminal_Offenses_Reported_by_Local_State_Police['Rape'] + Criminal_Offenses_Reported_by_Local_State_Police['Statutory rape'] + Criminal_Offenses_Reported_by_Local_State_Police['Fondling'] + Criminal_Offenses_Reported_by_Local_State_Police['Incest']
Criminal_Offenses_Reported_by_Local_State_Police['Burglary/Break ins'] =  Criminal_Offenses_Reported_by_Local_State_Police['Burglary']  
Criminal_Offenses_Reported_by_Local_State_Police['Motor vehicle theft'] = Criminal_Offenses_Reported_by_Local_State_Police['Motor vehicle theft']
Criminal_Offenses_Reported_by_Local_State_Police['Violent Crime'] = Criminal_Offenses_Reported_by_Local_State_Police['Robbery'] + Criminal_Offenses_Reported_by_Local_State_Police['Murder/Non-negligent manslaughter'] + Criminal_Offenses_Reported_by_Local_State_Police['Negligent manslaughter'] + Criminal_Offenses_Reported_by_Local_State_Police['Aggravated assault']
Criminal_Offenses_Reported_by_Local_State_Police = Criminal_Offenses_Reported_by_Local_State_Police[['index','Burglary/Break ins','Motor vehicle theft','Violent Crime','Rape','Statutory rape','Fondling']]
Criminal_Offenses_Reported_by_Local_State_Police = Criminal_Offenses_Reported_by_Local_State_Police.fillna(0)


c2 = pd.merge(Criminal_Offenses_Noncampus,Criminal_Offenses_On_campus_Student_Housing_Facilities,on = "index", how = "outer", suffixes = ("_NC","_SHF"))
c3 = pd.merge(c2,Criminal_Offenses_Public_Property,on = "index",how = "outer",suffixes = ("","_PP"))
c4 = pd.merge(c3,Criminal_Offenses_On_campus,on = "index",how = "outer",suffixes = ("","_OC"))
c5 = pd.merge(c4,Criminal_Offenses_Reported_by_Local_State_Police,on = "index",how = "outer",suffixes = ("","_RLSP"))
c5 = c5.fillna(0)
c5['Rape'] = c5["Rape_NC"] +c5["Rape_SHF"]+c5["Rape_OC"]+c5["Rape_RLSP"]+c5["Rape"]
c5['Statutory rape'] = c5["Statutory rape_NC"] +c5["Statutory rape_SHF"]+c5["Statutory rape_OC"]+c5["Statutory rape_RLSP"]+c5["Statutory rape"]



c5['Burglary/Break ins'] = c5["Burglary/Break ins_NC"] +c5["Burglary/Break ins_SHF"]+c5["Burglary/Break ins_OC"]+c5["Burglary/Break ins_RLSP"]+c5["Burglary/Break ins"]
c5['Violent Crime'] = c5["Violent Crime_NC"] +c5["Violent Crime_SHF"]+c5["Violent Crime_OC"]+c5["Violent Crime_RLSP"]+c5["Violent Crime"]
c5['Motor vehicle theft'] = c5["Motor vehicle theft_NC"] +c5["Motor vehicle theft_SHF"]+c5["Motor vehicle theft_OC"]+c5["Motor vehicle theft_RLSP"]+c5["Motor vehicle theft"]
c5['Fondling'] = c5["Fondling_NC"] +c5["Fondling_SHF"]+c5["Fondling_OC"]+c5["Fondling_RLSP"]+c5["Fondling"]
c5 = c5[['index','Rape_NC','Rape_OC','Statutory rape_NC','Statutory rape_OC','Burglary/Break ins_NC','Burglary/Break ins_OC','Violent Crime_NC','Violent Crime_OC','Motor vehicle theft_NC','Motor vehicle theft_OC','Fondling_NC','Fondling_OC']]

In [6]:
#Violence Against Women act offences custom columns
VAWA_Offenses_Reported_by_Local_State_Police['VAWA_Offenses_Reported_by_Local_State_Police'] = VAWA_Offenses_Reported_by_Local_State_Police['Domestic violence'] + VAWA_Offenses_Reported_by_Local_State_Police['Dating violence'] + VAWA_Offenses_Reported_by_Local_State_Police['Stalking']
VAWA_Offenses_Noncampus['VAWA_Offenses_Noncampus'] = VAWA_Offenses_Noncampus['Domestic violence'] + VAWA_Offenses_Noncampus['Dating violence'] + VAWA_Offenses_Noncampus['Stalking']
VAWA_Offenses_On_campus['VAWA_Offenses_On_campus'] = VAWA_Offenses_On_campus['Domestic violence'] + VAWA_Offenses_On_campus['Dating violence'] + VAWA_Offenses_On_campus['Stalking']
VAWA_Offenses_On_campus_Student_Housing_Facilities['VAWA_Offenses_On_campus_Student_Housing_Facilities'] = VAWA_Offenses_On_campus_Student_Housing_Facilities['Domestic violence'] + VAWA_Offenses_On_campus_Student_Housing_Facilities['Dating violence'] + VAWA_Offenses_On_campus_Student_Housing_Facilities['Stalking']
VAWA_Offenses_Public_Property['VAWA_Offenses_Public_Property'] = VAWA_Offenses_Public_Property['Domestic violence'] + VAWA_Offenses_Public_Property['Dating violence'] + VAWA_Offenses_Public_Property['Stalking']


v2 = pd.merge(VAWA_Offenses_Noncampus,VAWA_Offenses_On_campus_Student_Housing_Facilities,on = "index", how = "outer", suffixes = ("_NC","_SHF"))
v3 = pd.merge(v2,VAWA_Offenses_Public_Property,on = "index",how = "outer",suffixes = ("","_PP"))
v4 = pd.merge(v3,VAWA_Offenses_On_campus,on = "index",how = "outer",suffixes = ("","_OC"))
v5 = pd.merge(v4,VAWA_Offenses_Reported_by_Local_State_Police,on = "index",how = "outer",suffixes = ("","_RLSP"))
v5 = v5.fillna(0)
#v5['VAWA Offenses (Total)'] = v5['VAWA_Offenses_Noncampus'].astype(int) + v5['VAWA_Offenses_On_campus_Student_Housing_Facilities'].astype(int) + v5['VAWA_Offenses_On_campus'].astype(int) + v5['VAWA_Offenses_Public_Property'].astype(int) + v5['VAWA_Offenses_Reported_by_Local_State_Police'].astype(int)
v5 = v5[['index','VAWA_Offenses_On_campus','VAWA_Offenses_Noncampus']]

In [7]:
#Printing out all the hate crimes
my_list = list(Hate_Crimes_Noncampus)

print (my_list)

['Murder/Non-negligent manslaughter', 'Murder/Non-negligent manslaughter - Race', 'Murder/Non-negligent manslaughter - Religion', 'Murder/Non-negligent manslaughter - Sexual orientation', '\tMurder/Non-negligent manslaughter - Gender', 'Murder/Non-negligent manslaughter - Gender Identity', ' Murder/Non-negligent manslaughter - Disability', ' \tMurder/Non-negligent manslaughter - Ethnicity/National origin', 'Murder/Non-negligent manslaughter - Ethnicity', 'Murder/Non-negligent manslaughter - National origin', 'Negligent manslaughter', 'Negligent manslaughter - Race', 'Negligent manslaughter - Religion', 'Negligent manslaughter - Sexual orientation', 'Negligent manslaughter - Gender', '\tNegligent manslaughter - Disability', ' Negligent manslaughter - Ethnicity/National origin', 'Sex offenses - Forcible', 'Sex offenses - Forcible - Race', ' Sex offenses - Forcible - Religion', 'Sex offenses - Forcible - Sexual orientation', 'Sex offenses - Forcible - Gender', '\tSex offenses - Forcible - Disability', 'Sex offenses - Forcible - Ethnicity/National origin', 'Sex offenses - Non-forcible', 'Sex offenses - Non-forcible -Race', 'Sex offenses - Non-forcible - Religion', 'Sex offenses - Non-forcible - Sexual orientation', 'Sex offenses - Non-forcible - Gender', '\tSex offenses - Non-forcible - Disability', 'Sex offenses - Non-forcible - Ethnicity/National origin', '\tRape', 'Rape - Race', ' Rape - Religion', 'Rape - Forcible - Sexual orientation', 'Rape - Gender', 'Rape - Gender Identity', '\tRape - Disability', 'Rape - Ethnicity', 'Rape - National origin', 'Fondling', 'Fondling - Race', ' Fondling - Religion', 'Fondling - Forcible - Sexual orientation', 'Fondling - Gender', 'Fondling - Gender Identity', '\tFondling - Disability', 'Fondling - Ethnicity', 'Fondling - National origin', 'Incest', 'Incest - Race', ' Incest - Religion', 'Incest - Forcible - Sexual orientation', 'Incest - Gender', 'Incest - Gender Identity', '\tIncest - Disability', 'Incest - Ethnicity', 'Incest - National origin', 'Statutory rape', 'Statutory rape - Race', ' Statutory rape - Religion', 'Statutory rape - Forcible - Sexual orientation', 'Statutory rape - Gender', 'Statutory rape - Gender Identity', '\tStatutory rape - Disability', 'Statutory rape - Ethnicity', 'Statutory rape - National origin', 'Robbery', 'Robbery - Race', 'Robbery - Religion', 'Robbery - Sexual orientation', 'Robbery - Gender', 'Robbery - Gender Identity', 'Robbery - Disability', 'Robbery - Ethnicity/National origin', 'Robbery - Ethnicity', 'Robbery - National origin', 'Aggravated assault', 'Aggravated assault - Race', 'Aggravated assault - Religion', 'Aggravated assault - Sexual orientation', 'Aggravated assault - Gender', 'Aggravated assault - Gender Identity', 'Aggravated assault - Disability', 'Aggravated assault - Ethnicity/National origin', 'Aggravated assault - Ethnicity', 'Aggravated assault - National origin', 'Burglary', 'Burglary - Race', 'Burglary - Religion', 'Burglary - Sexual orientation', 'Burglary - Gender', 'Burglary - Gender Identity', 'Burglary - Disability', 'Burglary - Ethnicity/National origin', 'Burglary - Ethnicity', 'Burglary - National origin', 'Motor vehicle theft', 'Motor vehicle theft - Race', 'Motor vehicle theft - Religion', 'Motor vehicle theft - Sexual orientation', 'Motor vehicle theft - Gender', 'Motor vehicle theft - Gender Identity', 'Motor vehicle theft - Disability', 'Motor vehicle theft - Ethnicity/National origin', 'Motor vehicle theft - Ethnicity', 'Motor vehicle theft - National origin', 'Arson', 'Arson - Race', 'Arson - Religion', 'Arson - Sexual orientation', 'Arson - Gender', 'Arson - Gender Identity', 'Arson - Disability', 'Arson - Ethnicity/National origin', 'Arson - Ethnicity', 'Arson - National origin', 'Simple assault', 'Simple assault - Race', 'Simple assault - Religion', 'Simple assault - Sexual orientation', 'Simple assault - Gender', 'Simple assault - Gender Identity', 'Simple assault - Disability', 'Simple assault - Ethnicity/National origin', 'Simple assault - Ethnicity', 'Simple assault - National origin', 'Larceny-theft', 'Larceny-theft - Race', 'Larceny-theft - Religion', 'Larceny-theft - Sexual orientation', 'Larceny-theft - Gender', 'Larceny-theft - Gender Identity', 'Larceny-theft - Disability', 'Larceny-theft - Ethnicity/National origin', 'Larceny-theft - Ethnicity', 'Larceny-theft - National origin', 'Intimidation', 'Intimidation - Race', 'Intimidation - Religion', 'Intimidation - Sexual orientation', 'Intimidation - Gender', 'Intimidation - Gender Identity', 'Intimidation - Disability', 'Intimidation - Ethnicity/National origin', 'Intimidation - Ethnicity', 'Intimidation - National origin', 'Destruction/damage/ vandalism of property', 'Destruction/damage/ vandalism of property - Race', 'Destruction/damage/ vandalism of property - Religion', 'Destruction/damage/ vandalism of property - Sexual orientation', 'Destruction/damage/ vandalism of property - Gender', 'Destruction/damage/ vandalism of property - Gender Identity', 'Destruction/damage/ vandalism of property - Disability', 'Destruction/damage/ vandalism of property - Ethnicity/National origin', 'Destruction/damage/ vandalism of property - Ethnicity', 'Destruction/damage/ vandalism of property - National origin', 'index']

In [8]:
#fills out empty in Hate Crimes and also drops unrequired detail (everything after -)
Hate_Crimes_Noncampus = Hate_Crimes_Noncampus[Hate_Crimes_Noncampus.columns.drop(list(Hate_Crimes_Noncampus.filter(regex=' - ')))]
Hate_Crimes_Noncampus = Hate_Crimes_Noncampus.fillna(0)
Hate_Crimes_On_campus = Hate_Crimes_On_campus[Hate_Crimes_On_campus.columns.drop(list(Hate_Crimes_On_campus.filter(regex=' - ')))]
Hate_Crimes_On_campus = Hate_Crimes_On_campus.fillna(0)

In [9]:
Hate_Crimes_On_campus

,Murder/Non-negligent manslaughter,Negligent manslaughter,\tRape,Fondling,Incest,Statutory rape,Robbery,Aggravated assault,Burglary,Motor vehicle theft,Arson,Simple assault,Larceny-theft,Intimidation,Destruction/damage/ vandalism of property,index
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"A T Still University of Health Sciences,Missou..."
1,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Aaniiih Nakoda College,Aaniiih Nakoda College,..."
2,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Abilene Christian University,ACU-Abilene,4673...."
3,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Abraham Baldwin Agricultural College,ABAC main..."
4,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Abraham Baldwin Agricultural College,ABAC on t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145212,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,3"
145213,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,4"
145214,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Zane State College,Main Campus,2262.0,2019,204..."
145215,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"Zane State College,The Willett-Pratt Training ..."
145216,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,"ZMS The Academy,Main Campus,125.0,2019,486248,1"

In [10]:
#Combines all of hate crimes into simple columns
Hate_Crimes_Noncampus['Hate_Crimes_Noncampus']=Hate_Crimes_Noncampus.sum(axis=1)
Hate_Crimes_Noncampus = Hate_Crimes_Noncampus[['index','Hate_Crimes_Noncampus']]
Hate_Crimes_On_campus_Student_Housing_Facilities['Hate_Crimes_On_campus_Student_Housing_Facilities']=Hate_Crimes_On_campus_Student_Housing_Facilities.sum(axis=1)
Hate_Crimes_On_campus_Student_Housing_Facilities = Hate_Crimes_On_campus_Student_Housing_Facilities[['index','Hate_Crimes_On_campus_Student_Housing_Facilities']]
Hate_Crimes_Public_Property['Hate_Crimes_Public_Property']=Hate_Crimes_Public_Property.sum(axis=1)
Hate_Crimes_Public_Property = Hate_Crimes_Public_Property[['index','Hate_Crimes_Public_Property']]
Hate_Crimes_On_campus['Hate_Crimes_On_campus']=Hate_Crimes_On_campus.sum(axis=1)
Hate_Crimes_On_campus = Hate_Crimes_On_campus[['index','Hate_Crimes_On_campus']]
Hate_Crimes_Reported_by_Local_State_Police['Hate_Crimes_Reported_by_Local_State_Police']=Hate_Crimes_Reported_by_Local_State_Police.sum(axis=1)
Hate_Crimes_Reported_by_Local_State_Police = Hate_Crimes_Reported_by_Local_State_Police[['index','Hate_Crimes_Reported_by_Local_State_Police']]
h2 = pd.merge(Hate_Crimes_Reported_by_Local_State_Police,Hate_Crimes_Public_Property ,on = "index",how = "outer",suffixes = ("_LSP","_PP"))
h3 = pd.merge(h2,Hate_Crimes_On_campus ,on = "index",how = "outer",suffixes = ("","_OC"))
h4 = pd.merge(h3,Hate_Crimes_On_campus_Student_Housing_Facilities ,on = "index",how = "outer",suffixes = ("","_SHF"))
h5 = pd.merge(h4,Hate_Crimes_Noncampus ,on = "index",how = "outer",suffixes = ("","_NC"))
h5 = h5.fillna(0)

#h5['Hate Crimes_OC'] = h5['Hate_Crimes_On_campus'] + h5['Hate_Crimes_Reported_by_Local_State_Police'] + h5['Hate_Crimes_Public_Property']  +h5['Hate_Crimes_On_campus_Student_Housing_Facilities'] +h5['Hate_Crimes_Noncampus'] 

h5 = h5.fillna(0)
h5 = h5[['index', 'Hate_Crimes_On_campus','Hate_Crimes_Noncampus']]

In [11]:
#Merges all crimes on index
ac = pd.merge(arrests,c5 ,on = "index",how = "outer")
acv = pd.merge(ac,v5 ,on = "index",how = "outer")
acvd = pd.merge(acv,d5 ,on = "index",how = "outer")
acvdh5 = pd.merge(acvd,h5 ,on = "index",how = "outer")      
acvdh5 = acvdh5.fillna(0)
finaly = acvdh5
finaly[['Institution_Name', 'Campus_Name','Size','Year','ID','CampusID']] = finaly['index'].str.split(',',  expand=True)
#College,Campus_Name,size,year,Id,CampusID
finaly
first_column = finaly.pop('CampusID') 
finaly.insert(0, 'CampusID', first_column)
first_column = finaly.pop('ID') 
finaly.insert(0, 'ID', first_column)
first_column = finaly.pop('Year') 
finaly.insert(0, 'Year', first_column)
first_column = finaly.pop('Size') 
finaly.insert(0, 'Size', first_column)
first_column = finaly.pop('Campus_Name') 
finaly.insert(0, 'Campus_Name', first_column)
first_column = finaly.pop('Institution_Name') 
finaly.insert(0, 'Institution_Name', first_column)

In [12]:
#Code to download file (For use if required)
#finaly.to_csv('college_final.csv',index = False)

In [13]:

#final customization of the dataframe including sorting

#pd.set_option('display.width', None)
#pd.set_option('display.max_colwidth', None)
finaly = finaly[finaly.Size != 'nan']
finaly = finaly.loc[finaly['Year'].astype(int) > 2010]
#finaly.loc[finaly['Size'].str.contains(".0") == False]
finaly['Testing'] = finaly['Institution_Name'] + finaly['Campus_Name'] + finaly['Year'] + finaly['CampusID'] + finaly['ID']

finaly = finaly.loc[finaly.duplicated(subset=['Testing']) == False]
finaly = finaly.rename(columns = {'VAWA Offenses (Total)':'Violence Against Women Act Offenses'})
#finaly.to_csv('CrimeDatafinal.csv',index = False)
finaly.drop('Testing', axis=1, inplace=True)
finaly.rename(columns={'Arrests-Liquor Law/Drug Abuse Violation': 'Arrests-Liquor Law/Drug Abuse Violation_NC', 'Arrests-Weapon Possession': 'Arrests-Weapon Possession_NC','Hate_Crimes_On_campus':'Hate_Crimes_OC','Hate_Crimes_Noncampus':'Hate_Crimes_NC','VAWA_Offenses_Noncampus':'VAWA_Offenses_NC','VAWA_Offenses_On_campus':'VAWA_Offenses_OC'}, inplace=True)
pd.set_option('display.max_columns', None)

In [14]:
#finaly.to_csv('locTotal.csv',index = False)

In [15]:
#Inspecting Column Names
my_list = list(finaly)

print (my_list)

['Institution_Name', 'Campus_Name', 'Size', 'Year', 'ID', 'CampusID', 'index', 'Arrests-Liquor Law/Drug Abuse Violation_OC', 'Arrests-Liquor Law/Drug Abuse Violation_NC', 'Arrests-Weapon Possession_OC', 'Arrests-Weapon Possession_NC', 'Rape_NC', 'Rape_OC', 'Statutory rape_NC', 'Statutory rape_OC', 'Burglary/Break ins_NC', 'Burglary/Break ins_OC', 'Violent Crime_NC', 'Violent Crime_OC', 'Motor vehicle theft_NC', 'Motor vehicle theft_OC', 'Fondling_NC', 'Fondling_OC', 'VAWA_Offenses_OC', 'VAWA_Offenses_NC', 'Disciplinary_Actions-Liquor Law/Drug Abuse Violation_NC', 'Disciplinary_Actions-Liquor Law/Drug Abuse Violation_OC', 'Disciplinary_Actions-Weapon Possession_NC', 'Disciplinary_Actions-Weapon Possession_OC', 'Hate_Crimes_OC', 'Hate_Crimes_NC']

In [16]:
#finalyz = finaly.loc[finaly['Year'].astype(int)  == 2019]
#n = len(pd.unique(finalyz['ID']))
  
#print("No.of.unique values :", 
     # n)

In [17]:
#finaly.sum()

In [18]:
finaly

,Institution_Name,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation_OC,Arrests-Liquor Law/Drug Abuse Violation_NC,Arrests-Weapon Possession_OC,Arrests-Weapon Possession_NC,Rape_NC,Rape_OC,Statutory rape_NC,Statutory rape_OC,Burglary/Break ins_NC,Burglary/Break ins_OC,Violent Crime_NC,Violent Crime_OC,Motor vehicle theft_NC,Motor vehicle theft_OC,Fondling_NC,Fondling_OC,VAWA_Offenses_OC,VAWA_Offenses_NC,Disciplinary_Actions-Liquor Law/Drug Abuse Violation_NC,Disciplinary_Actions-Liquor Law/Drug Abuse Violation_OC,Disciplinary_Actions-Weapon Possession_NC,Disciplinary_Actions-Weapon Possession_OC,Hate_Crimes_OC,Hate_Crimes_NC
60941,A T Still University of Health Sciences,Missouri Campus,3293.0,2011,177834,1,"A T Still University of Health Sciences,Missou...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60942,A T Still University of Health Sciences,Arizona Campus,3293.0,2011,177834,2,"A T Still University of Health Sciences,Arizon...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60943,Aaniiih Nakoda College,Aaniiih Nakoda College,169.0,2011,180203,1,"Aaniiih Nakoda College,Aaniiih Nakoda College,...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60944,ABC Beauty Academy,Main Campus,34.0,2011,459523,1,"ABC Beauty Academy,Main Campus,34.0,2011,459523,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60945,Abcott Institute,Main Campus,83.0,2011,461892,1,"Abcott Institute,Main Campus,83.0,2011,461892,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145208,Z Hair Academy,Z Hair Academy,146.0,2019,451237,3,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145209,Z Hair Academy,Z Hair Academy,146.0,2019,451237,4,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,4",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145210,Zane State College,Main Campus,2262.0,2019,204255,1,"Zane State College,Main Campus,2262.0,2019,204...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145211,Zane State College,The Willett-Pratt Training Center,2262.0,2019,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145212,ZMS The Academy,Main Campus,125.0,2019,486248,1,"ZMS The Academy,Main Campus,125.0,2019,486248,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
#Seperating into two dataframes for on and off campus
finaly.columns[finaly.columns.str.contains(pat = '_OC') ] 

OC = finaly[['Institution_Name','Campus_Name','Size','Year','ID','CampusID','index','Arrests-Liquor Law/Drug Abuse Violation_OC',
       'Arrests-Weapon Possession_OC', 'Rape_OC', 'Statutory rape_OC',
       'Burglary/Break ins_OC', 'Violent Crime_OC', 'Motor vehicle theft_OC',
       'Fondling_OC', 'VAWA_Offenses_OC',
       'Disciplinary_Actions-Liquor Law/Drug Abuse Violation_OC',
       'Disciplinary_Actions-Weapon Possession_OC', 'Hate_Crimes_OC']]
NC = finaly[['Institution_Name','Campus_Name','Size','Year','ID','CampusID','index','Arrests-Liquor Law/Drug Abuse Violation_NC',
       'Arrests-Weapon Possession_NC', 'Rape_NC', 'Statutory rape_NC',
       'Burglary/Break ins_NC', 'Violent Crime_NC', 'Motor vehicle theft_NC',
       'Fondling_NC', 'VAWA_Offenses_NC',
       'Disciplinary_Actions-Liquor Law/Drug Abuse Violation_NC',
       'Disciplinary_Actions-Weapon Possession_NC', 'Hate_Crimes_NC']]

In [20]:
#Ignore Warning
#Adding a column that says on/off campus for both dataframes
OC["location"] = "On Campus"
NC["location"] = "Non Campus"

<ipython-input-20-bf730504d702>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  OC["location"] = "On Campus"
<ipython-input-20-bf730504d702>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NC["location"] = "Non Campus"

In [21]:
#Removing column header
OC.columns = OC.columns.str.rstrip('_OC')
NC.columns = NC.columns.str.rstrip('_NC')
OC

,Institution_Name,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Rape,Statutory rape,Burglary/Break ins,Violent Crime,Motor vehicle theft,Fondling,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,location
60941,A T Still University of Health Sciences,Missouri Campus,3293.0,2011,177834,1,"A T Still University of Health Sciences,Missou...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
60942,A T Still University of Health Sciences,Arizona Campus,3293.0,2011,177834,2,"A T Still University of Health Sciences,Arizon...",0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,On Campus
60943,Aaniiih Nakoda College,Aaniiih Nakoda College,169.0,2011,180203,1,"Aaniiih Nakoda College,Aaniiih Nakoda College,...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
60944,ABC Beauty Academy,Main Campus,34.0,2011,459523,1,"ABC Beauty Academy,Main Campus,34.0,2011,459523,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
60945,Abcott Institute,Main Campus,83.0,2011,461892,1,"Abcott Institute,Main Campus,83.0,2011,461892,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145208,Z Hair Academy,Z Hair Academy,146.0,2019,451237,3,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
145209,Z Hair Academy,Z Hair Academy,146.0,2019,451237,4,"Z Hair Academy,Z Hair Academy,146.0,2019,451237,4",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
145210,Zane State College,Main Campus,2262.0,2019,204255,1,"Zane State College,Main Campus,2262.0,2019,204...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
145211,Zane State College,The Willett-Pratt Training Center,2262.0,2019,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus
145212,ZMS The Academy,Main Campus,125.0,2019,486248,1,"ZMS The Academy,Main Campus,125.0,2019,486248,1",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,On Campus

In [22]:
#Simple addition of two dataframes (top to bottom)
finaly = NC.append(OC)

In [23]:
#Sorting Values
finaly = finaly.sort_values('index')
finaly = finaly[['Institution_Name','location', 'Campus_Name', 'Size', 'Year', 'ID', 'CampusID',
       'index', 'Arrests-Liquor Law/Drug Abuse Violation',
       'Arrests-Weapon Possession', 'Rape', 'Statutory rape',
       'Burglary/Break ins', 'Violent Crime', 'Motor vehicle theft',
       'Fondling', 'VAWA_Offenses',
       'Disciplinary_Actions-Liquor Law/Drug Abuse Violation',
       'Disciplinary_Actions-Weapon Possession', 'Hate_Crimes' ]]
finaly.columns

Index(['Institution_Name', 'location', 'Campus_Name', 'Size', 'Year', 'ID',
       'CampusID', 'index', 'Arrests-Liquor Law/Drug Abuse Violation',
       'Arrests-Weapon Possession', 'Rape', 'Statutory rape',
       'Burglary/Break ins', 'Violent Crime', 'Motor vehicle theft',
       'Fondling', 'VAWA_Offenses',
       'Disciplinary_Actions-Liquor Law/Drug Abuse Violation',
       'Disciplinary_Actions-Weapon Possession', 'Hate_Crimes'],
      dtype='object')

In [24]:
#finaly.to_csv('Total.csv',index = False)

In [25]:
finaly

finaly.loc[finaly['Institution_Name'].str.contains("georgia instit", case=False)]

,Institution_Name,location,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Rape,Statutory rape,Burglary/Break ins,Violent Crime,Motor vehicle theft,Fondling,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes
137865,Georgia Institute of Cosmetology,Non Campus,GEORGIA INSTITUTE OF COSMETOLOGY (BUFORD),252.0,2019,408862,2,"Georgia Institute of Cosmetology,GEORGIA INSTI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
137865,Georgia Institute of Cosmetology,On Campus,GEORGIA INSTITUTE OF COSMETOLOGY (BUFORD),252.0,2019,408862,2,"Georgia Institute of Cosmetology,GEORGIA INSTI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63493,Georgia Institute of Cosmetology,On Campus,GEORGIA INSTITUTE OF COSMETOLOGY (BUFORD),286.0,2011,408862,2,"Georgia Institute of Cosmetology,GEORGIA INSTI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63493,Georgia Institute of Cosmetology,Non Campus,GEORGIA INSTITUTE OF COSMETOLOGY (BUFORD),286.0,2011,408862,2,"Georgia Institute of Cosmetology,GEORGIA INSTI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97261,Georgia Institute of Cosmetology,Non Campus,GEORGIA INSTITUTE OF COSMETOLOGY (BUFORD),297.0,2015,408862,2,"Georgia Institute of Cosmetology,GEORGIA INSTI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116783,Georgia Institute of Technology-Main Campus,On Campus,Main Campus,29376.0,2017,139755,1,"Georgia Institute of Technology-Main Campus,Ma...",14.0,2.0,4.0,0.0,17.0,9.0,10.0,8.0,19.0,191.0,0.0,0.0
127170,Georgia Institute of Technology-Main Campus,On Campus,Main Campus,32723.0,2018,139755,1,"Georgia Institute of Technology-Main Campus,Ma...",20.0,1.0,5.0,0.0,58.0,1.0,9.0,6.0,15.0,202.0,1.0,0.0
127170,Georgia Institute of Technology-Main Campus,Non Campus,Main Campus,32723.0,2018,139755,1,"Georgia Institute of Technology-Main Campus,Ma...",0.0,0.0,4.0,0.0,7.0,0.0,0.0,3.0,1.0,16.0,0.0,0.0
137868,Georgia Institute of Technology-Main Campus,Non Campus,Main Campus,36302.0,2019,139755,1,"Georgia Institute of Technology-Main Campus,Ma...",2.0,0.0,1.0,0.0,11.0,0.0,4.0,1.0,0.0,16.0,0.0,0.0
137868,Georgia Institute of Technology-Main Campus,On Campus,Main Campus,36302.0,2019,139755,1,"Georgia Institute of Technology-Main Campus,Ma...",17.0,7.0,7.0,0.0,25.0,3.0,26.0,3.0,17.0,324.0,0.0,0.0

In [26]:
finaly
finaly['Sex Offences'] = finaly['Rape'] + finaly['Statutory rape'] + finaly['Fondling']

In [27]:
finaly = finaly.drop(['Rape','Statutory rape','Fondling'],axis = 1)

In [28]:
finaly.loc[finaly['Hate_Crimes']>0]

,Institution_Name,location,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences
124086,ASA College,On Campus,Dania Beach Campus,4356.0,2018,404994,3,"ASA College,Dania Beach Campus,4356.0,2018,404...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
124085,ASA College,On Campus,Manhattan,4356.0,2018,404994,2,"ASA College,Manhattan,4356.0,2018,404994,2",0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
104008,ATI College-Norwalk,On Campus,Main Campus,64.0,2016,444325,1,"ATI College-Norwalk,Main Campus,64.0,2016,4443...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
68613,Abilene Christian University,On Campus,ACU-Abilene,4367.0,2012,222178,1,"Abilene Christian University,ACU-Abilene,4367....",1.0,0.0,7.0,2.0,2.0,0.0,34.0,0.0,1.0,0.0
103615,Academy of Art University,On Campus,Main Campus,12608.0,2016,108232,1,"Academy of Art University,Main Campus,12608.0,...",0.0,0.0,5.0,4.0,0.0,19.0,67.0,2.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68595,York College of Pennsylvania,On Campus,York College of Pennsylvania,5605.0,2011,217059,1,"York College of Pennsylvania,York College of P...",21.0,0.0,4.0,3.0,0.0,0.0,551.0,0.0,2.0,0.0
123658,York County School of Technology-Adult & Conti...,On Campus,Main Campus,104.0,2017,418409,1,York County School of Technology-Adult & Conti...,2.0,1.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0
145199,Youngstown State University,Non Campus,Main Campus,12110.0,2019,206695,1,"Youngstown State University,Main Campus,12110....",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
123661,Youngstown State University,Non Campus,Main Campus,12521.0,2017,206695,1,"Youngstown State University,Main Campus,12521....",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
68607,Zane State College,On Campus,Main Campus,2943.0,2011,204255,1,"Zane State College,Main Campus,2943.0,2011,204...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [29]:
topHund = pd.read_csv("/Users/adi/Desktop/" + "school_and_country_table.csv")
topHund = topHund['school_name']

In [30]:
topHund = topHund.head(100)
topHund

0                        Harvard University
1        California Institute of Technology
2     Massachusetts Institute of Technology
3                       Stanford University
4                      Princeton University
                      ...
95                    University of Arizona
96                      University of Basel
97     University of Maryland, College Park
98                        Dartmouth College
99         École Normale Supérieure de Lyon
Name: school_name, Length: 100, dtype: object

In [31]:
list(topHund)
t50 = (finaly[finaly["Institution_Name"].isin(topHund)])
t50

,Institution_Name,location,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences
85951,Boston University,Non Campus,Boston University Charles River Campus,32112.0,2014,164988,1,"Boston University,Boston University Charles Ri...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85951,Boston University,On Campus,Boston University Charles River Campus,32112.0,2014,164988,1,"Boston University,Boston University Charles Ri...",20.0,1.0,18.0,6.0,1.0,23.0,1094.0,3.0,1.0,12.0
94977,Boston University,Non Campus,Boston University Charles River Campus,32158.0,2015,164988,1,"Boston University,Boston University Charles Ri...",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94977,Boston University,On Campus,Boston University Charles River Campus,32158.0,2015,164988,1,"Boston University,Boston University Charles Ri...",15.0,0.0,19.0,7.0,1.0,21.0,790.0,2.0,1.0,13.0
77413,Boston University,On Campus,Boston University Charles River Campus,32411.0,2013,164988,1,"Boston University,Boston University Charles Ri...",7.0,0.0,22.0,6.0,0.0,0.0,782.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68583,Yeshiva University,Non Campus,WILF CAMPUS,6563.0,2011,197708,1,"Yeshiva University,WILF CAMPUS,6563.0,2011,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76661,Yeshiva University,Non Campus,WILF CAMPUS,6740.0,2012,197708,1,"Yeshiva University,WILF CAMPUS,6740.0,2012,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76661,Yeshiva University,On Campus,WILF CAMPUS,6740.0,2012,197708,1,"Yeshiva University,WILF CAMPUS,6740.0,2012,197...",0.0,0.0,9.0,2.0,0.0,0.0,8.0,0.0,2.0,0.0
85146,Yeshiva University,On Campus,WILF CAMPUS,6747.0,2013,197708,1,"Yeshiva University,WILF CAMPUS,6747.0,2013,197...",0.0,0.0,5.0,1.0,0.0,0.0,8.0,1.0,0.0,0.0
85146,Yeshiva University,Non Campus,WILF CAMPUS,6747.0,2013,197708,1,"Yeshiva University,WILF CAMPUS,6747.0,2013,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
flagShips_MajorState_Big = ["University of Alabama",
             "University of Arizona", 
            "University of California-Berkeley", "University of Florida", "University of Georgia","University of Illinois Urbana-Champaign","University of Hawaii at Manoa","University of Idaho","University of Michigan-Ann Arbor", "Amherst", "University of North Carolina at Chapel Hill","Texas A&M University","Texas Tech","University of Washington-Seattle","Ohio State University-Main Campus","Amherst College","University of California-Davis","Pennsylvania State University-Main Campus","Emory","New York University","Liberty University","Southern New Hampshire University","Boston University","Johns Hopkins","University of Central Florida","Texas A&M University","Arizona State University-Tempe","University of Texas—Austin","Liberty University","Howard University","West Point","Georgetown University", "Ivy Tech Community College","Southern New Hampshire","North Carolina A & T State UniversityArizona State University-Tempe","Ashford University","Grand Canyon University","Pennsylvania State University-Main Campus","University of North Carolina at Charlotte","University of Minnesota-Twin Cities","University of California-","University of Alabama-","Northeastern University","University of Maine","Florida Agricultural and Mechanical University","Texas Southern University","Wesleyan University","Rutgers University-New Brunswick","Reed College","Pomona College","Swarthmore College","Baylor University","University of North Georgia","Florida SouthWestern State College","Utah Valley University","York College of Pennsylvania","Brite Divinity School","Pontifical John Paul II Institute for Studies","Roger Williams University School of Law","College of the Ozarks","Brigham Young University-Idaho","University of South Carolina-Columbia","College of the Holy Cross","Bard College","Georgia Institute of Technology-Main Campus"]
Big_Major = pd.DataFrame(flagShips_MajorState_Big, columns=['Name'])
Big_Major

big = finaly[finaly['Institution_Name'].str.contains(fr"{'|'.join(flagShips_MajorState_Big)}")]
big = big[big["Institution_Name"].str.contains("Henry|Health|West Liberty|Massachusetts-Amherst|Maine | Wesleyan") == False]
big.Institution_Name.unique()

array(['Amherst College', 'Arizona State University-Tempe',
       'Ashford University', "Bard College at Simon's Rock",
       'Bard College', 'Baylor University', 'Boston University',
       'Brigham Young University-Idaho', 'Brite Divinity School',
       'College of the Holy Cross', 'College of the Ozarks',
       'Emory University', 'Emory University-Oxford College',
       'Florida Agricultural and Mechanical University',
       'Florida SouthWestern State College', 'Georgetown University',
       'Georgia Institute of Technology-Main Campus',
       'Grand Canyon University', 'Howard University',
       'Ivy Tech Community College', 'Johns Hopkins University',
       'Liberty University', 'Longy School of Music of Bard College',
       'New York University', 'Northeastern University',
       'Ohio State University-Main Campus',
       'Pennsylvania State University-Main Campus', 'Pomona College',
       'Pontifical John Paul II Institute for Studies on Marriage and Family',
       'Reed College', 'Roger Williams University School of Law',
       'Rutgers University-New Brunswick',
       'Southern New Hampshire University', 'Swarthmore College',
       'Texas A&M University-San Antonio',
       'Texas A&M University-Texarkana', 'Texas Southern University',
       'Texas Tech University', 'The University of Alabama',
       'University of Alabama at Birmingham',
       'University of Alabama in Huntsville', 'University of Arizona',
       'University of Arizona-South', 'University of California-Berkeley',
       'University of California-Davis',
       'University of California-Hastings College of Law',
       'University of California-Irvine',
       'University of California-Los Angeles',
       'University of California-Merced',
       'University of California-Riverside',
       'University of California-San Diego',
       'University of California-San Francisco',
       'University of California-Santa Barbara',
       'University of California-Santa Cruz',
       'University of Central Florida', 'University of Florida',
       'University of Georgia', 'University of Hawaii at Manoa',
       'University of Idaho', 'University of Maine',
       'University of Michigan-Ann Arbor',
       'University of Minnesota-Twin Cities',
       'University of North Carolina at Chapel Hill',
       'University of North Carolina at Charlotte',
       'University of North Georgia',
       'University of South Carolina-Columbia',
       'University of Washington-Seattle Campus',
       'Utah Valley University', 'Wesleyan University',
       'York College of Pennsylvania'], dtype=object)

In [33]:
#Only including universities with 2000+ students
finalyz = finaly.loc[(finaly['Size'].astype(float) > 2000)]
finalyz

,Institution_Name,location,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences
94156,A T Still University of Health Sciences,Non Campus,Adelante Campus,3357.0,2015,177834,3,"A T Still University of Health Sciences,Adelan...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94156,A T Still University of Health Sciences,On Campus,Adelante Campus,3357.0,2015,177834,3,"A T Still University of Health Sciences,Adelan...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103585,A T Still University of Health Sciences,On Campus,Adelante Campus,3569.0,2016,177834,3,"A T Still University of Health Sciences,Adelan...",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103585,A T Still University of Health Sciences,Non Campus,Adelante Campus,3569.0,2016,177834,3,"A T Still University of Health Sciences,Adelan...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123677,A T Still University of Health Sciences,Non Campus,Adelante Campus,3717.0,2018,177834,3,"A T Still University of Health Sciences,Adelan...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103582,Zane State College,Non Campus,The Willett-Pratt Training Center,3362.0,2015,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85172,Zane State College,Non Campus,The Willett-Pratt Training Center,3652.0,2013,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85172,Zane State College,On Campus,The Willett-Pratt Training Center,3652.0,2013,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94153,Zane State College,Non Campus,The Willett-Pratt Training Center,4009.0,2014,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94153,Zane State College,On Campus,The Willett-Pratt Training Center,4009.0,2014,204255,2,"Zane State College,The Willett-Pratt Training ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
finalyz.loc[(((finalyz['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'].astype(int))/finalyz['Size'].astype(float) ))> 1]

finalyz.loc[(((finalyz['Arrests-Liquor Law/Drug Abuse Violation'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Arrests-Weapon Possession'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Burglary/Break ins'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Violent Crime'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Motor vehicle theft'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['VAWA_Offenses'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Disciplinary_Actions-Weapon Possession'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Hate_Crimes'].astype(int))/finalyz['Size'].astype(float) ))> 1]
finalyz.loc[(((finalyz['Sex Offences'].astype(int))/finalyz['Size'].astype(float) ))> 1]

Empty DataFrame
Columns: [Institution_Name, location, Campus_Name, Size, Year, ID, CampusID, index, Arrests-Liquor Law/Drug Abuse Violation, Arrests-Weapon Possession, Burglary/Break ins, Violent Crime, Motor vehicle theft, VAWA_Offenses, Disciplinary_Actions-Liquor Law/Drug Abuse Violation, Disciplinary_Actions-Weapon Possession, Hate_Crimes, Sex Offences]
Index: []

In [35]:
High_Sex_Offences = finalyz.loc[(((finalyz['Sex Offences'].astype(int))/finalyz['Size'].astype(float) ))> 0.0084]
High_Sex_Offences = High_Sex_Offences['Institution_Name'].unique()
High_Sex_Offences = (finalyz[finalyz["Institution_Name"].isin(High_Sex_Offences)])

High_Hate_Crimes = finalyz.loc[(((finalyz['Hate_Crimes'].astype(int))/finalyz['Size'].astype(float) ))> 0.0015]
High_Hate_Crimes = High_Hate_Crimes['Institution_Name'].unique()
High_Hate_Crimes = (finalyz[finalyz["Institution_Name"].isin(High_Hate_Crimes)])

Disciplinary_ActionsWeaponPossession = finalyz.loc[(((finalyz['Disciplinary_Actions-Weapon Possession'].astype(int))/finalyz['Size'].astype(float) ))> 0.0035]
Disciplinary_ActionsWeaponPossession = Disciplinary_ActionsWeaponPossession['Institution_Name'].unique()
Disciplinary_ActionsWeaponPossession = (finalyz[finalyz["Institution_Name"].isin(Disciplinary_ActionsWeaponPossession)])

VAWA_Offenses = finalyz.loc[(((finalyz['VAWA_Offenses'].astype(int))/finalyz['Size'].astype(float) ))> 0.007]
VAWA_Offenses = VAWA_Offenses['Institution_Name'].unique()
VAWA_Offenses = (finalyz[finalyz["Institution_Name"].isin(VAWA_Offenses)])
VAWA_Offenses['Institution_Name'].unique()

Motorvehicletheft = finalyz.loc[(((finalyz['Motor vehicle theft'].astype(int))/finalyz['Size'].astype(float) ))> 0.002199]
Motorvehicletheft = Motorvehicletheft['Institution_Name'].unique()
Motorvehicletheft = (finalyz[finalyz["Institution_Name"].isin(Motorvehicletheft)])
Motorvehicletheft['Institution_Name'].unique()

ViolentCrime = finalyz.loc[(((finalyz['Violent Crime'].astype(int))/finalyz['Size'].astype(float) ))> 0.0053]
ViolentCrime = ViolentCrime['Institution_Name'].unique()
ViolentCrime = (finalyz[finalyz["Institution_Name"].isin(ViolentCrime)])
ViolentCrime['Institution_Name'].unique()

Burglarly = finalyz.loc[(((finalyz['Burglary/Break ins'].astype(int))/finalyz['Size'].astype(float) ))> 0.00975]
Burglarly = Burglarly['Institution_Name'].unique()
Burglarly = (finalyz[finalyz["Institution_Name"].isin(Burglarly)])
Burglarly['Institution_Name'].unique()

Arrests_Weapons = finalyz.loc[(((finalyz['Arrests-Weapon Possession'].astype(int))/finalyz['Size'].astype(float) ))> 0.0035]
Arrests_Weapons = Arrests_Weapons['Institution_Name'].unique()
Arrests_Weapons = (finalyz[finalyz["Institution_Name"].isin(Arrests_Weapons)])
Arrests_Weapons['Institution_Name'].unique()

Arrests_Liquor = finalyz.loc[(((finalyz['Arrests-Liquor Law/Drug Abuse Violation'].astype(int))/finalyz['Size'].astype(float) ))> 0.15]
Arrests_Liquor = Arrests_Liquor['Institution_Name'].unique()
Arrests_Liquor = (finalyz[finalyz["Institution_Name"].isin(Arrests_Liquor)])
Arrests_Liquor['Institution_Name'].unique()

DA_Liquor = finalyz.loc[(((finalyz['Disciplinary_Actions-Liquor Law/Drug Abuse Violation'].astype(int))/finalyz['Size'].astype(float) ))> 0.15]
DA_Liquor = DA_Liquor['Institution_Name'].unique()
DA_Liquor = (finalyz[finalyz["Institution_Name"].isin(DA_Liquor)])
DA_Liquor['Institution_Name'].unique()

array(['Assumption College', 'Augustana College', 'Bryant University',
       'Bucknell University', 'Carthage College',
       'College of the Holy Cross', 'Colorado College', 'Curry College',
       'Denison University', 'Drew University', 'Eckerd College',
       'Fairfield University', 'Franklin Pierce University',
       'Gettysburg College', 'High Point University',
       'Hobart William Smith Colleges', 'Illinois Wesleyan University',
       'Keene State College', 'Lewis & Clark College',
       'Macalester College', 'Merrimack College', 'Occidental College',
       'Plymouth State University', 'Providence College',
       'Saint Ambrose University', 'Saint Johns University',
       'Siena College', 'Springfield College',
       'St Bonaventure University', 'Stonehill College',
       'Trinity College', 'Union College',
       'University of California-Santa Cruz', 'Vassar College',
       'Wesleyan University', 'Willamette University'], dtype=object)

In [36]:
df = pd.concat([DA_Liquor,Arrests_Liquor,Arrests_Weapons,Burglarly,ViolentCrime,Motorvehicletheft,Disciplinary_ActionsWeaponPossession,VAWA_Offenses,High_Hate_Crimes,High_Sex_Offences,big,t50],ignore_index = True)
df = df.drop_duplicates()
z = df['Institution_Name'].unique()
count = pd.DataFrame(z, columns=['Name'])
#df.to_excel (r'/Users/adi/Desktop/cleaned.xlsx', index = False, header=True)
#df.to_excel (r'/Users/adi/Desktop/cou.xlsx', index = False, header=True)

In [37]:
n = len(pd.unique(df['Institution_Name']))
  
print("No.of.unique values :", n)

No.of.unique values : 266

In [38]:
df

,Institution_Name,location,Campus_Name,Size,Year,ID,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences
0,Assumption College,Non Campus,Main Campus,2428.0,2018,164562,1,"Assumption College,Main Campus,2428.0,2018,164...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Assumption College,On Campus,Main Campus,2428.0,2018,164562,1,"Assumption College,Main Campus,2428.0,2018,164...",0.0,0.0,2.0,4.0,0.0,13.0,130.0,2.0,1.0,11.0
2,Assumption College,Non Campus,Main Campus,2443.0,2019,164562,1,"Assumption College,Main Campus,2443.0,2019,164...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Assumption College,On Campus,Main Campus,2443.0,2019,164562,1,"Assumption College,Main Campus,2443.0,2019,164...",0.0,1.0,6.0,0.0,1.0,8.0,93.0,3.0,0.0,7.0
4,Assumption College,On Campus,Main Campus,2481.0,2017,164562,1,"Assumption College,Main Campus,2481.0,2017,164...",1.0,0.0,1.0,2.0,0.0,8.0,142.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13307,Yeshiva University,Non Campus,WILF CAMPUS,6563.0,2011,197708,1,"Yeshiva University,WILF CAMPUS,6563.0,2011,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13308,Yeshiva University,Non Campus,WILF CAMPUS,6740.0,2012,197708,1,"Yeshiva University,WILF CAMPUS,6740.0,2012,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13309,Yeshiva University,On Campus,WILF CAMPUS,6740.0,2012,197708,1,"Yeshiva University,WILF CAMPUS,6740.0,2012,197...",0.0,0.0,9.0,2.0,0.0,0.0,8.0,0.0,2.0,0.0
13310,Yeshiva University,On Campus,WILF CAMPUS,6747.0,2013,197708,1,"Yeshiva University,WILF CAMPUS,6747.0,2013,197...",0.0,0.0,5.0,1.0,0.0,0.0,8.0,1.0,0.0,0.0
13311,Yeshiva University,Non Campus,WILF CAMPUS,6747.0,2013,197708,1,"Yeshiva University,WILF CAMPUS,6747.0,2013,197...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
loc = pd.read_excel("/Users/adi/Desktop/IPEDS_data.xlsx")
loc

,ID number,Name,year,ZIP code,Highest degree offered,County name,Longitude location of institution,Latitude location of institution,Religious affiliation,Offers Less than one year certificate,Offers One but less than two years certificate,Offers Associate's degree,Offers Two but less than 4 years certificate,Offers Bachelor's degree,Offers Postbaccalaureate certificate,Offers Master's degree,Offers Post-master's certificate,Offers Doctor's degree - research/scholarship,Offers Doctor's degree - professional practice,Offers Doctor's degree - other,Offers Other degree,Applicants total,Admissions total,Enrolled total,Percent of freshmen submitting SAT scores,Percent of freshmen submitting ACT scores,SAT Critical Reading 25th percentile score,SAT Critical Reading 75th percentile score,SAT Math 25th percentile score,SAT Math 75th percentile score,SAT Writing 25th percentile score,SAT Writing 75th percentile score,ACT Composite 25th percentile score,ACT Composite 75th percentile score,"Estimated enrollment, total","Estimated enrollment, full time","Estimated enrollment, part time","Estimated undergraduate enrollment, total","Estimated undergraduate enrollment, full time","Estimated undergraduate enrollment, part time","Estimated freshman undergraduate enrollment, total","Estimated freshman enrollment, full time","Estimated freshman enrollment, part time","Estimated graduate enrollment, total","Estimated graduate enrollment, full time","Estimated graduate enrollment, part time",Associate's degrees awarded,Bachelor's degrees awarded,Master's degrees awarded,Doctor's degrese - research/scholarship awarded,Doctor's degrees - professional practice awarded,Doctor's degrees - other awarded,Certificates of less than 1-year awarded,Certificates of 1 but less than 2-years awarded,Certificates of 2 but less than 4-years awarded,Postbaccalaureate certificates awarded,Post-master's certificates awarded,Number of students receiving an Associate's degree,Number of students receiving a Bachelor's degree,Number of students receiving a Master's degree,Number of students receiving a Doctor's degree,Number of students receiving a certificate of less than 1-year,Number of students receiving a certificate of 1 but less than 4-years,Number of students receiving a Postbaccalaureate or Post-master's certificate,Percent admitted - total,Admissions yield - total,"Tuition and fees, 2010-11","Tuition and fees, 2011-12","Tuition and fees, 2012-13","Tuition and fees, 2013-14",Total price for in-state students living on campus 2013-14,Total price for out-of-state students living on campus 2013-14,State abbreviation,FIPS state code,Geographic region,Sector of institution,Level of institution,Control of institution,Historically Black College or University,Tribal college,Degree of urbanization (Urban-centric locale),Carnegie Classification 2010: Basic,Total enrollment,Full-time enrollment,Part-time enrollment,Undergraduate enrollment,Graduate enrollment,Full-time undergraduate enrollment,Part-time undergraduate enrollment,Percent of total enrollment that are American Indian or Alaska Native,Percent of total enrollment that are Asian,Percent of total enrollment that are Black or African American,Percent of total enrollment that are Hispanic/Latino,Percent of total enrollment that are Native Hawaiian or Other Pacific Islander,Percent of total enrollment that are White,Percent of total enrollment that are two or more races,Percent of total enrollment that are Race/ethnicity unknown,Percent of total enrollment that are Nonresident Alien,Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of total enrollment that are women,Percent of undergraduate enrollment that are American Indian or Alaska Native,Percent of undergraduate enrollment that are Asian,Percent of undergraduate enrollment that are Black or African American,Percent of undergraduate enrollment that are Hispanic/Latino,Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander,Percent of undergraduate enrollment that are White,Percent of undergraduate enrollment that are two or more races,Percent of undergraduate enrollment that are Race/ethnicity unknown,Percent of undergraduate enrollment that are Nonresident Alien,Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of undergraduate enrollment that are women,Percent of graduate enrollment that are American Indian or Alaska Native,Percent of graduate enrollment that are Asian,Percent of graduate enrollment that are Black or African American,Percent of graduate enrollment that are Hispanic/Latino,Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander,Percent of graduate enrollment that are White,Percent of graduate enrollment that are two or more races,Percent of graduate enrollment that are Race/ethnicity unknown,Percent of graduate enrollment that are Nonresident Alien,Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of graduate enrollment that are women,Number of first-time undergraduates - in-state,Percent of first-time undergraduates - in-state,Number of first-time undergraduates - out-of-state,Percent of first-time undergraduates - out-of-state,Number of first-time undergraduates - foreign countries,Percent of first-time undergraduates - foreign countries,Number of first-time undergraduates - residence unknown,Percent of first-time undergraduates - residence unknown,"Graduation rate - Bachelor degree within 4 years, total","Graduation rate - Bachelor degree within 5 years, total","Graduation rate - Bachelor degree within 6 years, total",Percent of freshmen receiving any financial aid,"Percent of freshmen receiving federal, state, local or institutional grant aid",Percent of freshmen receiving federal grant aid,Percent of freshmen receiving Pell grants,Percent of freshmen receiving other federal grant aid,Percent of freshmen receiving state/local grant aid,Percent of freshmen receiving institutional grant aid,Percent of freshmen receiving student loan aid,Percent of freshmen receiving federal student loans,Percent of freshmen receiving other loan aid,Endowment assets (year end) per FTE enrollment (GASB),Endowment assets (year end) per FTE enrollment (FASB)
0,100654,Alabama A & M University,2013,35762,Doctor's degree - research/scholarship,Madison County,-86.568502,34.783368,Not applicable,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Yes,Implied no,Yes,Implied no,Implied no,Implied no,6142.0,5521.0,1104.0,15.0,88.0,370.0,450.0,350.0,450.0,NaN,NaN,15.0,19.0,5024.0,4442.0,582.0,4055.0,3802.0,253.0,1104.0,1089.0,15.0,969.0,640.0,329.0,0.0,604.0,213.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,604.0,213.0,8.0,0.0,0.0,9.0,90.0,20.0,5800.0,6828.0,7182.0,7182.0,21849.0,27441.0,Alabama,Alabama,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Public, 4-year or above",Four or more years,Public,Yes,No,City: Midsize,Master's Colleges and Universities (larger pro...,5020.0,4439.0,581.0,4051.0,969.0,3799.0,252.0,0.0,1.0,92.0,1.0,0.0,5.0,0.0,1.0,0.0,1.0,55.0,0.0,0.0,95.0,1.0,0.0,3.0,0.0,1.0,0.0,0.0,51.0,0.0,2.0,81.0,1.0,0.0,15.0,0.0,1.0,0.0,2.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,23.0,29.0,97.0,89.0,81.0,81.0,7.0,1.0,32.0,89.0,89.0,1.0,NaN,NaN
1,100663,University of Alabama at Birmingham,2013,35294-0110,Doctor's degree - research/scholarship and pro...,Jefferson County,-86.809170,33.502230,Not applicable,Implied no,Yes,Implied no,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Implied no,5689.0,4934.0,1773.0,6.0,93.0,520.0,640.0,520.0,650.0,NaN,NaN,22.0,28.0,18568.0,11961.0,6607.0,11502.0,8357.0,3145.0,1773.0,1732.0,41.0,7066.0,3604.0,3462.0,0.0,2195.0,1540.0,147.0,387.0,8.0,0.0,20.0,0.0,23.0,47.0,0.0,2159.0,1533.0,542.0,0.0,20.0,70.0,87.0,36.0,5806.0,6264.0,6798.0,7206.0,22495.0,31687.0,Alabama,Alabama,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Public, 4-year or above",Four or more years,Public,No,No,City: Midsize,Research Universities (very high research acti...,18568.0,11961.0,6607.0,11502.0,7066.0,8357.0,3145.0,0.0,5.0,21.0,3.0,0.0,64.0,3.0,1.0,3.0,5.0,61.0,0.0,5.0,26.0,3.0,0.0,60.0,3.0,1.0,2.0,5.0,58.0,0.0,4.0,14.0,3.0,0.0,70.0,2.0,1.0,6.0,4.0,64.0,1529.0,86.0,224.0,13.0,19.0,1.0,1.0,0.0,29.0,46.0,53.0,90.0,79.0,36.0,36.0,10.0,0.0,60.0,56.0,55.0,5.0,24136.0,NaN
2,100690,Amridge University,2013,36117-3553,Doctor's degree - research/scholarship and pro...,Montgomery County,-86.174010,32.362609,Churches of Christ,Implied no,Implied no,Yes,Implied no,Yes,Implied no,Yes,Implied no,Yes,Yes,Implied no,Implied no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,626.0,326.0,300.0,313.0,202.0,111.0,6.0,3.0,3.0,313.0,124.0,189.0,5.0,68.0,68.0,2.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,68.0,60.0,10.0,0.0,0.0,0.0,NaN,NaN,8360.0,8720.0,6800.0,6870.0,NaN,NaN,Alabama,Alabama,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,No,No,City: Midsize,Baccalaureate Colleges--Arts & Sciences,631.0,323.0,308.0,322.0,309.0,202.0,120.0,0.0,0.0,40.0,1.0,0.0,30.0,0.0,28.0,0.0,0.0,58.0,0.0,0.0,42.0,1.0,0.0,29.0,0.0,27.0,0.0,1.0,61.0,0.0,0.0,37.0,1.0,0.0,32.0,0.0,29.0,0.0,0.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,67.0,100.0,90.0,90.0,90.0,0.0,40.0,90.0,100.0,100.0,0.0,NaN,302.0
3,100706,University of Alabama in Huntsville,2013,35899,Doctor's degree - research/scholarship and pro...,Madison County,-86.638420,34.722818,Not applicable,Yes,Implied no,Implied no,Implied no,Yes,Yes,Yes,Yes,Yes,Yes,Implied no,Implied no,2054.0,1656.0,651.0,34.0,94.0,510.0,640.0,510.0,650.0,NaN,NaN,23.0,29.0,7376.0,4802.0,2574.0,5696.0,4237.0,1459.0,651.0,638.0,13.0,1680.0,565.0,1115.0,0.0,1099.0,444.0,28.0,10.0,0.0,0.0,0.0,0.0,24.0,5.0,0.0,1091.0,444.0,38.0,0.0,0.0,28.0,81.0,39.0,7492.0,8094.0,8794.0,9192.0,23466.0,35780.0,Alabama,Alabama,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Public, 4-year or above",Four or more years,Public,No,No,City: Midsize,Research Universities (very high research acti...,7376.0,4802.0,2574.0,5696.0,1680.0,4237.0,1459.0,1.0,4.0,12.0,3.0,0.0,69.0,1.0,3.0,6.0,4.0,44.0,1.0,4.0,13.0,3.0,0.0,70.0,2.0,3.0,4.0,4.0,44.0,1.0,4.0,7.0,2.0,0.0,69.0,1.0,3.0,14.0,4.0,43.0,514.0,79.0,92.0,14.0,27.0,4.0,18.0,3.0,16.0,37.0,48.0,87.0,77.0,31.0,31.0,4.0,1.0,63.0,46.0,46.0,3.0,11502.0,NaN
4,100724,Alabama State University,2013,36104-0271,Doctor's degree - research/scholarship and pro...,Montgomery County,-86.295677,32.364317,Not applicable,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Yes,Yes,Yes,Yes,Implied no,Implied no,10245.0,5251.0,1479.0,18.0,87.0,380.0,480.0,370.0,480.0,NaN,NaN,15.0,19.0,6076.0,5183.0,893.0,5357.0,4873.0,484.0,1542.0,1517.0,25.0,719.0,310.0,409.0,0.0,600.0,147.0,3.0,45.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,599.0,147.0,48.0,0.0,0.0,27.0,51.0,28.0,7164.0,8082.0,7932.0,8720.0,18286.0,25222.0,Alabama,Alabama,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Public, 4-year or above",Four or more years,Public,Yes,No,City: Midsize,Master's Colleges and Universities (larger pro...,6075.0,5182.0,893.0,5356.0,719.0,4872.0,484.0,0.0,0.0,91.0,1.0,0.0,3.0,1.0,1.0,2.0,0.0,61.0,0.0,0.0,93.0,1.0,0.0,2.0,1.0,1.0,2.0,0.0,59.0,1.0,1.0,77.0,1.0,0.0,17.0,1.0,1.0,1.0,1.0,71.0,903.0,58.0,571.0,37.0,67.0,4.0,4.0,0.0,9.0,19.0,25.0,93.0,87.0,76.0,76.0,13.0,11.0,34.0,81.0,81.0,0.0,13202.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,451671,University of South Florida-Sarasota-Manatee,2013,34243-2049,Master's degree,Manatee County,-82.562951,27.391766,Not applicable,Implied no,Implied no,Yes,Implied no,Yes,Yes,Yes,Yes,Implied no,Implied no,Implied no,Implied no,393.0,136.0,86.0,79.0,59.0,502.0,580.0,490.0,570.0,490.0,570.0,22.0,25.0,1889.0,873.0,1016.0,1739.0,835.0,904.0,86.0,82.0,4.0,150.0,38.0,112.0,0.0,556.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,554.0,60.0,0.0,0.0,0.0,0.0,35.0,63.0,NaN,NaN,NaN,5587.0,NaN,NaN,Florida,Florida,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Public, 4-year or above",Four or more years,Public,No,No,Suburb: Large,Master's Colleges and Universities (medium pro...,1877.0,875.0,1002.0,1728.0,149.0,837.0,891.0,0.0,2.0,6.0,13.0,0.0,73.0,2.0,2.0,1.0,3.0,60.0,0.0,2.0,7.0,13.0,0.0,73.0,2.0,2.0,1.0,3.0,59.0,1.0,2.0,5.0,9.0,1.0,74.0,1.0,1.0,4.0,3.0,65.0,78.0,94.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4422.0,NaN
1530,454184,The Kingâ€™s College,2013,10004,Bachelor's degree,New York County,-74.012348,40.706861,Interdenominational,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Implied no,Implied no,Implied no,Implied no,Implied no,Implied no,3033.0,2158.0,127.0,57.0,45.0,540.0,630.0,510.0,600.0,520.0,640.0,24.0,28.0,504.0,489.0,15.0,504.0,489.0,15.0,127.0,125.0,2.0,NaN,NaN,NaN,0.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75.0,0.0,0.0,0.0,0.0,0.0,71.0,6.0,27350.0,29240.0,29240.0,31300.0,48717.0,48717.0,New York,New York,Mid East DE DC MD NJ NY PA,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,No,No,City: Large,Baccalaureate Colleges--Arts & Sciences,516.0,493.0,23.0,516.0,0.0,493.0,23.0,0.0,3.0,3.0,8.0,0.0,78.0,5.0,0.0,3.0,3.0,60.0,0.0,3.0,3.0,8.0,0.0,78.0,5.0,0.0,3.0,3.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,61.0,61.0,100.0,100.0,34.0,34.0,10.0,4.0,100.0,57.0,56.0,12.0,NaN,935.0
1531,454582,Ottawa University-Online,2013,66067,Master's degree,Franklin County,-95.263775,38.602692,American Baptist,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Yes,Implied no,Implied no,Implied no,Implied no,Implied no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.0,2.0,443.0,379.0,1.0,378.0,11.0,0.0,11.0,66.0,1.0,65.0,0.0,167.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167.0,36.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kansas,Kansas,Plains IA KS MN MO NE ND SD,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,No,No,Town: Distant,Baccalaureate Colleges--Diverse Fields,458.0,1.0,457.0,383.0,75.0,1.0,382.0,8.0,3.0,14.0,5.0,0.0,61.0,0.0,10.0,0.0,3.0,61.0,7.0,3.0,14.0,5.0,0.0,60.0,0.0,10.0,0.0,3.0,61.0,12.0,3.0,11.0,4.0,0.0,65.0,0.0,5.0,0.0,3.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20863.0
1532,455770,Providence Christian College,2013,91104,Bachelor's degree,Los Angeles County,-118.118491,34.172750,Undenominational,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Implied no,Implied no,Implied no,Implied no,Implied no,Implied no,122.0,65.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,68.0,0.0,68.0,68.0,0.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,53.0,31.0,20444.0,21444.0,22686.0,24222.0,38602.0,38602.0,California,California,Far West AK CA HI NV OR WA,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,No,No,City: Midsize,Baccalaureate Colleges--Arts & Sciences,66.0,66.0,0.0,66.0,0.0,66.0,0.0,0.0,6.0,3.0,5.0,0.0,79.0,3.0,0.0,5.0,6.0,52.0,0.0,6.0,3.0,5.0,0.0,79.0,3.0,0.0,5.0,6.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,54.0,54.0,100.0,100.0,50.0,50.0,14.0,0.0,100.0,64.0,64.0,14.0,NaN,350.0
1533,456490,Polytechnic University of Puerto Rico-Orlando,2013,32825,Master's degree,Orange County,-81.254951,28.551470,Not applicable,Implied no,Implied no,Implied no,Implied no,Yes,Implied no,Yes,Implied no,Implied no,Implied no,Implied no,Implied no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0,33.0,95.0,83.0,16.0,67.0,1.0,1.0,0.0,45.0,17.0,28.0,0.0,19.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,14.0,0.0,0.0,0.0,0.0,NaN,NaN,10920.0,10920.0,10920.0,10920.0,NaN,NaN,Florida,Florida,Southeast AL AR FL GA KY LA MS NC SC TN VA WV,"Private not-for-profit, 4-year or above",Four or more years,Private not-for-profit,No,No,Suburb: Large,Baccalaureate Colleges--Diverse Fields,125.0,32.0,93.0,82.0,43.0,17.0,65.0,0.0,0.0,0.0,98.0,0.0,2.0,0.0,1.0,0.0,0.0,34.0,0.0,0.0,0.0,98.0,0.0,2.0,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,98.0,0.0,0.0,0.0,2.0,0.0,0.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.0,100.0,100.0,0.0,50.0,0.0,50.0,50.0,0.0,NaN,NaN

In [40]:
locy = loc[["ID number","Longitude location of institution","Latitude location of institution"]]
locy

,ID number,Longitude location of institution,Latitude location of institution
0,100654,-86.568502,34.783368
1,100663,-86.809170,33.502230
2,100690,-86.174010,32.362609
3,100706,-86.638420,34.722818
4,100724,-86.295677,32.364317
...,...,...,...
1529,451671,-82.562951,27.391766
1530,454184,-74.012348,40.706861
1531,454582,-95.263775,38.602692
1532,455770,-118.118491,34.172750
1533,456490,-81.254951,28.551470

In [41]:
locy
locy = locy.rename(columns = {'ID number':'ID'})
locy
#dataTypeSeries = df.dtypes
df['ID'] = df['ID'].astype(str).astype(int)

In [42]:
loc_Included = pd.merge(locy,df, on = "ID", how = "outer")

In [43]:
loc_Included

,ID,Longitude location of institution,Latitude location of institution,Institution_Name,location,Campus_Name,Size,Year,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences
0,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100654,-86.568502,34.783368,Alabama A & M University,On Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",17.0,3.0,3.0,8.0,2.0,0.0,53.0,1.0,0.0,0.0
2,100654,-86.568502,34.783368,Alabama A & M University,On Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",11.0,1.0,58.0,9.0,2.0,0.0,24.0,4.0,0.0,0.0
3,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,5020.0,2013,1,"Alabama A & M University,Main Campus,5020.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,482680,NaN,NaN,University of North Georgia,Non Campus,Oconee Campus,18782.0,2017,3,"University of North Georgia,Oconee Campus,1878...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11340,482680,NaN,NaN,University of North Georgia,On Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11341,482680,NaN,NaN,University of North Georgia,Non Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11342,482680,NaN,NaN,University of North Georgia,Non Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11343,482680,NaN,NaN,University of North Georgia,On Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0

In [44]:
z = loc_Included[loc_Included['Longitude location of institution'].isna()]
z = z[['Institution_Name','ID','Longitude location of institution','Latitude location of institution']]
result_df = z.drop_duplicates()
#print(z['Institution_Name'].nunique())
#result_df
#result_df.to_excel(r'Path where the exported excel file will be stored\File Name.xlsx', index = False)

In [45]:
Left = z.Institution_Name.unique()
Left
Left
#Left = pd.DataFrame(Left, columns=['digits', 'words'])
#Code language: JavaScript (javascript)
#Left

array(['Northeastern Oklahoma A&M College',
       'Oregon Health & Science University',
       'Enterprise State Community College', 'Guam Community College',
       'Inter American University of Puerto Rico-Barranquitas',
       'Loma Linda University', 'Rush University',
       'The Art Institute of Atlanta', 'Umpqua Community College',
       'AI Miami International University of Art and Design',
       'Atlanta Technical College', 'Bellingham Technical College',
       'Dewey University-Hato Rey', 'East Central Community College',
       'Highline College', 'Mt Hood Community College',
       'San Bernardino Valley College', 'The Art Institute of Houston',
       'Universal Technical Institute of Arizona Inc-Motorcycle Mechanics Institute Division',
       'Universal Technical Institute-Auto Motorcycle & Marine Mechanics Institute Division-Orlando',
       'University of Arkansas for Medical Sciences',
       'University of California-San Francisco',
       'University of Nebraska Medical Center',
       'University of Texas Southwestern Medical Center',
       'University of the Sciences',
       'West Coast University-Orange County',
       'Herkimer County Community College', 'College of Micronesia-FSM',
       'Eastern New Mexico University-Roswell Campus',
       'Louisiana State University-Eunice', 'Gateway Technical College',
       'Ashford University', 'Brite Divinity School',
       'Emory University-Oxford College',
       'Florida SouthWestern State College', 'Grand Canyon University',
       'Ivy Tech Community College',
       'Longy School of Music of Bard College',
       'Pontifical John Paul II Institute for Studies on Marriage and Family',
       'Roger Williams University School of Law',
       'Texas A&M University-San Antonio', 'University of Arizona-South',
       'University of California-Hastings College of Law',
       'University of California-Merced', 'University of North Georgia'],
      dtype=object)

In [46]:
includeMissing = pd.read_excel("/Users/adi/Desktop/MissingLoc.xlsx")

In [47]:
includeMissing = includeMissing[['ID','Longitude location of institution','Latitude location of institution']]
includeMissing.rename(columns={'Longitude location of institution':'Latitude location of institution', 'Latitude location of institution':'Longitude location of institution'}, inplace=True)

In [48]:
mergedLoc = pd.merge(loc_Included,includeMissing, on = "ID", how = "outer")

In [49]:
mergedLoc = mergedLoc.fillna(0)

In [50]:
mergedLoc

,ID,Longitude location of institution_x,Latitude location of institution_x,Institution_Name,location,Campus_Name,Size,Year,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences,Latitude location of institution_y,Longitude location of institution_y
0,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000
1,100654,-86.568502,34.783368,Alabama A & M University,On Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",17.0,3.0,3.0,8.0,2.0,0.0,53.0,1.0,0.0,0.0,0.0000,0.0000
2,100654,-86.568502,34.783368,Alabama A & M University,On Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",11.0,1.0,58.0,9.0,2.0,0.0,24.0,4.0,0.0,0.0,0.0000,0.0000
3,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000
4,100654,-86.568502,34.783368,Alabama A & M University,Non Campus,Main Campus,5020.0,2013,1,"Alabama A & M University,Main Campus,5020.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,482680,0.000000,0.000000,University of North Georgia,Non Campus,Oconee Campus,18782.0,2017,3,"University of North Georgia,Oconee Campus,1878...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.5279,-83.9844
11340,482680,0.000000,0.000000,University of North Georgia,On Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34.5279,-83.9844
11341,482680,0.000000,0.000000,University of North Georgia,Non Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.5279,-83.9844
11342,482680,0.000000,0.000000,University of North Georgia,Non Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.5279,-83.9844
11343,482680,0.000000,0.000000,University of North Georgia,On Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,34.5279,-83.9844

In [51]:
sum_column = mergedLoc["Latitude location of institution_x"] + mergedLoc["Latitude location of institution_y"]
mergedLoc["Latitude"] = sum_column
summed =  mergedLoc["Longitude location of institution_x"] + mergedLoc["Longitude location of institution_y"]
mergedLoc['Longitude'] = summed
mergedLoc = mergedLoc.drop(['Longitude location of institution_x', 'Latitude location of institution_x','Longitude location of institution_y', 'Latitude location of institution_y'], axis=1)

In [52]:
pd.set_option("display.max_rows", 200, "display.max_columns", None)
mergedLoc = mergedLoc.loc[mergedLoc['Year'].astype(int) != 0]

In [53]:
mergedLoc

,ID,Institution_Name,location,Campus_Name,Size,Year,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences,Latitude,Longitude
0,100654,Alabama A & M University,Non Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
1,100654,Alabama A & M University,On Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",17.0,3.0,3.0,8.0,2.0,0.0,53.0,1.0,0.0,0.0,34.783368,-86.568502
2,100654,Alabama A & M University,On Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",11.0,1.0,58.0,9.0,2.0,0.0,24.0,4.0,0.0,0.0,34.783368,-86.568502
3,100654,Alabama A & M University,Non Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
4,100654,Alabama A & M University,Non Campus,Main Campus,5020.0,2013,1,"Alabama A & M University,Main Campus,5020.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,482680,University of North Georgia,Non Campus,Oconee Campus,18782.0,2017,3,"University of North Georgia,Oconee Campus,1878...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.527900,-83.984400
11340,482680,University of North Georgia,On Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11341,482680,University of North Georgia,Non Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11342,482680,University of North Georgia,Non Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11343,482680,University of North Georgia,On Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,34.527900,-83.984400

In [56]:
mergedLoc

,ID,Institution_Name,location,Campus_Name,Size,Year,CampusID,index,Arrests-Liquor Law/Drug Abuse Violation,Arrests-Weapon Possession,Burglary/Break ins,Violent Crime,Motor vehicle theft,VAWA_Offenses,Disciplinary_Actions-Liquor Law/Drug Abuse Violation,Disciplinary_Actions-Weapon Possession,Hate_Crimes,Sex Offences,Latitude,Longitude
0,100654,Alabama A & M University,Non Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
1,100654,Alabama A & M University,On Campus,Main Campus,4853.0,2012,1,"Alabama A & M University,Main Campus,4853.0,20...",17.0,3.0,3.0,8.0,2.0,0.0,53.0,1.0,0.0,0.0,34.783368,-86.568502
2,100654,Alabama A & M University,On Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",11.0,1.0,58.0,9.0,2.0,0.0,24.0,4.0,0.0,0.0,34.783368,-86.568502
3,100654,Alabama A & M University,Non Campus,Main Campus,4922.0,2011,1,"Alabama A & M University,Main Campus,4922.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
4,100654,Alabama A & M University,Non Campus,Main Campus,5020.0,2013,1,"Alabama A & M University,Main Campus,5020.0,20...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.783368,-86.568502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,482680,University of North Georgia,Non Campus,Oconee Campus,18782.0,2017,3,"University of North Georgia,Oconee Campus,1878...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.527900,-83.984400
11340,482680,University of North Georgia,On Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11341,482680,University of North Georgia,Non Campus,Oconee Campus,19722.0,2018,3,"University of North Georgia,Oconee Campus,1972...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11342,482680,University of North Georgia,Non Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.527900,-83.984400
11343,482680,University of North Georgia,On Campus,Oconee Campus,19748.0,2019,3,"University of North Georgia,Oconee Campus,1974...",0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,34.527900,-83.984400

In [55]:
#mergedLoc.loc[mergedLoc['Institution_Name'].str.contains("georgia instit", case=False)]
#mergedLoc.to_excel (r'/Users/adi/Desktop/CollegeCrimeWithLocation.xlsx', index = False, header=True)